'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase-browser';
import PixWikiHeader, { type PixWikiPlanKey } from '@/components/pix/PixWikiHeader';
import PixWikiDashboardNav from '@/components/pix/PixWikiDashboardNav';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

type Source='all'|'pix_key'|'pix_link'|'checkout'|'api';
type Row={id:string;company_id:string;company_name:string;mp_payment_id:string|null;amount_cents:number;fee_amount_cents:number;net_amount_cents:number;status:string;source:string;provider:string;received_at:string};
type Company={id:string;name:string};
type Snap={billing:{plan:PixWikiPlanKey};companies:Company[]};
const TZ='America/Sao_Paulo';
function isoDate(d:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function money(c:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(c||0)/100)}
function dec(c:number){return (Number(c||0)/100).toFixed(2).replace('.',',')}
function dt(v:string){return new Date(v).toLocaleString('pt-BR',{timeZone:TZ,day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})}
function sourceLabel(v:string){return({pix_key:'Chave Pix',pix_link:'Pix Link',checkout:'Checkout',api:'API'} as Record<string,string>)[v]||v}
function csv(v:unknown){const s=String(v??'').replace(/"/g,'""');return `"${s}"`}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}

export default function PixWikiRelatoriosPage(){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter();const[dark,setDark]=useState(true),[loading,setLoading]=useState(true),[reportLoading,setReportLoading]=useState(false);const[snap,setSnap]=useState<Snap|null>(null),[rows,setRows]=useState<Row[]>([]),[company,setCompany]=useState('all'),[source,setSource]=useState<Source>('all');const today=isoDate(new Date()),monthStart=`${today.slice(0,7)}-01`;const[start,setStart]=useState(monthStart),[end,setEnd]=useState(today),[error,setError]=useState(''),[exporting,setExporting]=useState('');
 useEffect(()=>{const saved=localStorage.getItem('publicTheme');setDark(saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches);(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/pix/login');return}const active=localStorage.getItem('pixWikiActiveCompanyId');const{data,error}=await supabase.rpc('pixwiki_v2_dashboard_snapshot',{p_company_id:active||null});if(error)throw error;setSnap(data as Snap);setLoading(false)})().catch(()=>{setError('Não foi possível carregar relatórios.');setLoading(false)})},[router,supabase]);
 async function load(){if(end<start){setError('Escolha um período válido.');return}setReportLoading(true);setError('');try{const out:Row[]=[];for(let p=0;p<20;p++){const{data,error}=await supabase.rpc('pixwiki_report_receipts',{p_company_id:company==='all'?null:company,p_source:source,p_start_date:start,p_end_date:end}).range(p*1000,p*1000+999);if(error)throw error;const batch=(data||[]) as Row[];out.push(...batch);if(batch.length<1000)break;if(p===19)throw new Error('too_large')}setRows(out)}catch(e:any){setError(String(e?.message||'').includes('too_large')?'Relatório acima de 20 mil linhas. Reduza o período.':'Não foi possível carregar o relatório.')}finally{setReportLoading(false)}}
 useEffect(()=>{if(!loading&&snap)load()},[loading,snap,company,source,start,end]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({count:a.count+1,gross:a.gross+r.amount_cents,fees:a.fees+r.fee_amount_cents,net:a.net+r.net_amount_cents}),{count:0,gross:0,fees:0,net:0}),[rows]);
 function exportCsv(){setExporting('csv');try{const lines=[["Data/Hora","Empresa","Origem","Bruto","Tarifa","Líquido","ID MP"].map(csv).join(';'),...rows.map(r=>[dt(r.received_at),r.company_name,sourceLabel(r.source),dec(r.amount_cents),dec(r.fee_amount_cents),dec(r.net_amount_cents),r.mp_payment_id||''].map(csv).join(';'))];download(new Blob([`\uFEFF${lines.join('\r\n')}`],{type:'text/csv;charset=utf-8'}),`pixwiki-${start}-a-${end}.csv`)}finally{setExporting('')}}
 function exportPdf(){setExporting('pdf');try{const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFontSize(18);doc.setFont('helvetica','bold');doc.text('PixWiki · Relatório de recebimentos',14,16);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(`${start} a ${end} · ${rows.length} recebimentos · Líquido ${money(totals.net)}`,14,23);autoTable(doc,{startY:30,head:[['Data','Empresa','Origem','Bruto','Tarifa','Líquido','ID MP']],body:rows.map(r=>[dt(r.received_at),r.company_name,sourceLabel(r.source),money(r.amount_cents),money(r.fee_amount_cents),money(r.net_amount_cents),r.mp_payment_id||'—']),styles:{fontSize:7.5,cellPadding:2},headStyles:{fillColor:[16,185,129],textColor:[2,6,23]}});doc.save(`pixwiki-${start}-a-${end}.pdf`)}finally{setExporting('')}}
 if(loading||!snap)return <main className="min-h-screen bg-[#020617] text-white flex items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-white/15 border-t-emerald-400"/></main>;
 const page=dark?'bg-[#020617] text-white':'bg-[#f7f8fa] text-slate-900',card=dark?'border-white/10 bg-white/[0.035]':'border-black/10 bg-white shadow-sm',muted=dark?'text-white/55':'text-slate-500',input=dark?'border-white/10 bg-white/[0.05] text-white':'border-black/10 bg-white text-slate-900';
 return <main className={`min-h-screen pb-28 ${page}`}><div className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6"><PixWikiHeader plan={snap.billing.plan} dark={dark} onThemeChange={setDark}/><div className="mt-6"><h1 className="text-3xl font-black">Relatórios</h1><p className={`mt-2 text-sm ${muted}`}>Disponíveis em todas as faixas. Filtre Chave Pix, Link, Checkout e API.</p></div>{error&&<div className="mt-4 rounded-2xl border border-red-500/25 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
 <section className={`mt-6 rounded-3xl border p-5 ${card}`}><div className="grid gap-3 md:grid-cols-4"><label><span className={`text-xs font-bold ${muted}`}>De</span><input type="date" value={start} onChange={e=>setStart(e.target.value)} max={end} className={`mt-1 w-full rounded-xl border px-3 py-3 text-sm ${input}`}/></label><label><span className={`text-xs font-bold ${muted}`}>Até</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)} min={start} max={today} className={`mt-1 w-full rounded-xl border px-3 py-3 text-sm ${input}`}/></label><label><span className={`text-xs font-bold ${muted}`}>Empresa</span><select value={company} onChange={e=>setCompany(e.target.value)} className={`mt-1 w-full rounded-xl border px-3 py-3 text-sm ${input}`} style={{colorScheme:dark?'dark':'light'}}><option value="all">Todas</option>{snap.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className={`text-xs font-bold ${muted}`}>Origem</span><select value={source} onChange={e=>setSource(e.target.value as Source)} className={`mt-1 w-full rounded-xl border px-3 py-3 text-sm ${input}`} style={{colorScheme:dark?'dark':'light'}}><option value="all">Todas</option><option value="pix_key">Chave Pix</option><option value="pix_link">Pix Link</option><option value="checkout">Checkout</option><option value="api">API</option></select></label></div></section>
 <section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Pix',String(totals.count)],['Bruto',money(totals.gross)],['Tarifas',money(totals.fees)],['Líquido',money(totals.net)]].map(([a,b])=><div key={a} className={`rounded-2xl border p-5 ${card}`}><p className={`text-xs ${muted}`}>{a}</p><p className="mt-2 text-2xl font-black">{reportLoading?'…':b}</p></div>)}</section>
 <section className={`mt-4 overflow-hidden rounded-3xl border ${card}`}><div className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">Detalhamento</h2><p className={`text-xs ${muted}`}>{rows.length} recebimento(s)</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!rows.length||!!exporting} className={`rounded-xl border px-4 py-2.5 text-xs font-black disabled:opacity-40 ${card}`}>CSV</button><button onClick={exportPdf} disabled={!rows.length||!!exporting} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-40">PDF</button></div></div>{reportLoading?<div className="p-12 text-center">Carregando…</div>:!rows.length?<div className={`p-10 text-center text-sm ${muted}`}>Nenhum recebimento no período.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className={dark?'bg-white/[0.04]':'bg-slate-50'}><tr className={`text-left text-[10px] uppercase ${muted}`}><th className="px-4 py-3">Data</th><th className="px-4 py-3">Empresa</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3 text-right">Bruto</th><th className="px-4 py-3 text-right">Tarifa</th><th className="px-4 py-3 text-right">Líquido</th></tr></thead><tbody className={dark?'divide-y divide-white/5':'divide-y divide-black/5'}>{rows.slice(0,500).map(r=><tr key={r.id}><td className="px-4 py-3 whitespace-nowrap">{dt(r.received_at)}</td><td className="px-4 py-3">{r.company_name}</td><td className="px-4 py-3"><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-black text-emerald-400">{sourceLabel(r.source)}</span></td><td className="px-4 py-3 text-right font-bold">{money(r.amount_cents)}</td><td className="px-4 py-3 text-right">{money(r.fee_amount_cents)}</td><td className="px-4 py-3 text-right font-black text-emerald-400">{money(r.net_amount_cents)}</td></tr>)}</tbody></table></div>}</section>
 </div><PixWikiDashboardNav dark={dark}/></main>
}
