import "server-only";
import { db, checked, event } from "./server";
import { followupSnapshot } from "./outreach";
import { businessHours } from "./catalog";
import {
  sendEmail,
  sendWhatsapp,
  syncTemplate,
  threadHasReply,
  googleAccount,
} from "./channels";
import { discover } from "./providers";
import { reconcileSales } from "./sales";
export async function runWorker() {
  const d = db();
  const sales = await reconcileSales();
  // Only the threads generated by this SDR are checked. Never mine mailbox contacts.
  if (process.env.SDR_GOOGLE_ACCOUNT_ID) {
    const recent = checked(
      await d
        .from("sdr_queue")
        .select("lead_id,thread_id")
        .eq("status", "sent")
        .eq("channel", "email")
        .not("thread_id", "is", null)
        .gte("sent_at", new Date(Date.now() - 30 * 86400000).toISOString())
        .order("sent_at", { ascending: false })
        .limit(10),
    );
    await Promise.allSettled(
      (recent || []).map(async (q) => {
        try {
          if (await threadHasReply(q.thread_id)) {
            checked(
              await d.rpc("sdr_stop", {
                p_lead: q.lead_id,
                p_reason: "email_reply",
                p_suppress: false,
              }),
            );
            checked(
              await d
                .from("sdr_leads")
                .update({ last_inbound_at: new Date().toISOString() })
                .eq("id", q.lead_id),
            );
            checked(
              await d
                .from("sdr_opportunities")
                .update({ stage: "replied" })
                .eq("lead_id", q.lead_id)
                .in("stage", ["new", "contacted"]),
            );
          }
        } catch {
          /* Follow-up checks below fail closed if reply detection is unavailable. */
        }
      }),
    );
  }
  if (process.env.SDR_LIVE_SEND !== "true" || !businessHours())
    return { mode: "paused", sales, sent: 0 };
  const rows = checked(await d.rpc("sdr_claim"));
  let sent = 0;
  const results = [];
  for (const q of rows || []) {
    let sending = false;
    try {
      const o = checked(
        await d
          .from("sdr_opportunities")
          .select("*")
          .eq("id", q.opportunity_id)
          .single(),
      )!;
      const l = checked(
        await d.from("sdr_leads").select("*").eq("id", q.lead_id).single(),
      )!;
      const c = checked(
        await d
          .from("sdr_campaigns")
          .select("*")
          .eq("id", q.campaign_id)
          .single(),
      )!;
      if (q.channel === "whatsapp") {
        if ((await syncTemplate(o.product)).status !== "APPROVED")
          throw new Error("template_not_approved");
      } else {
        await googleAccount();
        if (q.step > 0) {
          const previous = checked(
            await d
              .from("sdr_queue")
              .select("thread_id")
              .eq("opportunity_id", o.id)
              .eq("status", "sent")
              .eq("channel", "email"),
          );
          for (const prev of previous || []) {
            if (!prev.thread_id || (await threadHasReply(prev.thread_id)))
              throw new Error("reply_or_thread_unavailable");
          }
        }
      }
      checked(await d.rpc("sdr_begin_send", { p_queue: q.id }));
      sending = true;
      const receipt =
        q.channel === "email"
          ? await sendEmail(q, o, l)
          : await sendWhatsapp(q, o, l);
      checked(
        await d
          .from("sdr_queue")
          .update({
            status: "sent",
            ...receipt,
            sent_at: new Date().toISOString(),
          })
          .eq("id", q.id),
      );
      checked(
        await d
          .from("sdr_leads")
          .update({ last_contact_at: new Date().toISOString() })
          .eq("id", l.id),
      );
      checked(
        await d
          .from("sdr_opportunities")
          .update({ stage: "contacted" })
          .eq("id", o.id)
          .eq("stage", "new"),
      );
      sent++;
      // At most one WhatsApp introduction. Follow-ups by email only; reply detection mandatory.
      if (q.channel === "email" && q.enqueue_mode !== "manual_pilot" && q.step + 1 < c.max_touches)
        checked(
          await d
            .from("sdr_queue")
            .upsert(
              {
                opportunity_id: o.id,
                lead_id: l.id,
                campaign_id: c.id,
                channel: "email",
                ...followupSnapshot(q),
                step: q.step + 1,
                due_at: new Date(Date.now() + 3 * 86400000).toISOString(),
              },
              {
                onConflict: "opportunity_id,channel,step",
                ignoreDuplicates: true,
              },
            ),
        );
      results.push({ id: q.id, status: "sent" });
    } catch (e) {
      const reason = e instanceof Error ? e.message : "send_failed";
      checked(
        await d
          .from("sdr_queue")
          .update({
            status: sending ? "unknown" : "blocked",
            error_code: reason,
          })
          .eq("id", q.id)
          .in("status", ["processing", "sending"]),
      );
      results.push({ id: q.id, status: sending ? "unknown" : "blocked" });
    }
  }
  // Discovery does not enqueue outreach; imported leads await campaign/fit review.
  const campaigns = checked(
    await d
      .from("sdr_campaigns")
      .select("id,product")
      .eq("enabled", true)
      .eq("auto_discover", true)
      .gt("trial_ends_at", new Date().toISOString())
      .or(
        `next_search_at.is.null,next_search_at.lte.${new Date().toISOString()}`,
      )
      .limit(1),
  );
  for (const c of campaigns || []) {
    try {
      const rollout = checked(
        await d
          .from("sdr_product_rollouts")
          .select("status,auto_discovery_enabled")
          .eq("product", c.product)
          .maybeSingle(),
      );
      if (!rollout || !["pilot", "active"].includes(rollout.status) || !rollout.auto_discovery_enabled) continue;
      await discover(c.id);
    } catch {
      await event("worker", "discovery_failed", null, null, {
        campaignId: c.id,
      });
    }
  }
  return { mode: "live", sales, sent, results };
}
