import { createClient } from 'jsr:@supabase/supabase-js@2'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const headers = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': 'https://pix.wiki',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

function base64url(bytes: Uint8Array) {
  let s = ''
  for (const b of bytes) s += String.fromCharCode(b)
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '')
}
function randomSecret(prefix: string) { const b=new Uint8Array(32);crypto.getRandomValues(b);return `${prefix}${base64url(b)}` }
async function sha256(value:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hmacHex(secret:string,value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function blockedIpv4(host:string){const m=host.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);if(!m)return false;const a=Number(m[1]),b=Number(m[2]);if([a,b,Number(m[3]),Number(m[4])].some(n=>n<0||n>255))return true;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}
function validateWebhookUrl(raw:string){let u:URL;try{u=new URL(raw)}catch{throw new Error('invalid_webhook_url')}if(u.protocol!=='https:'||u.username||u.password)throw new Error('invalid_webhook_url');if(u.port&&u.port!=='443')throw new Error('invalid_webhook_port');const host=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(!host||host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||host==='::1'||host.startsWith('fc')||host.startsWith('fd')||host.startsWith('fe80:')||blockedIpv4(host))throw new Error('private_webhook_host_not_allowed');return u.toString()}
async function getUser(s:any,req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return null;const {data,error}=await s.auth.getUser(token);return error?null:data?.user}
async function requireFeature(s:any,userId:string,feature='api'){const {data,error}=await s.rpc('pixwiki_has_feature_for_user',{p_user_id:userId,p_feature:feature});if(error)throw new Error('feature_check_failed');if(data!==true)throw new Error('pix_pro_required')}
async function companyAllowed(s:any,userId:string,companyId:string|null){if(!companyId)return true;const {data}=await s.from('companies').select('id').eq('id',companyId).eq('user_id',userId).eq('segment_key','pix_wiki').maybeSingle();return !!data}
async function sendTestWebhook(s:any,hook:any,secret:string){const url=validateWebhookUrl(String(hook.url)),eventId=crypto.randomUUID(),timestamp=Math.floor(Date.now()/1000).toString(),payload={event:'pix.received.test',id:eventId,created_at:new Date().toISOString(),test:true,data:{receipt_id:'test',company_id:hook.company_id??null,source:'pix_key',amount_cents:100,fee_amount_cents:0,net_amount_cents:100,status:'approved',received_at:new Date().toISOString()}},raw=JSON.stringify(payload),signature=await hmacHex(secret,`${timestamp}.${raw}`),started=Date.now();try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'PixWiki-Webhooks/1.0','X-PixWiki-Event':'pix.received.test','X-PixWiki-Event-Id':eventId,'X-PixWiki-Timestamp':timestamp,'X-PixWiki-Signature':`v1=${signature}`,'Idempotency-Key':eventId},body:raw,signal:AbortSignal.timeout(8000)});const body=(await r.text()).slice(0,500);await s.from('pixwiki_webhooks').update({last_status_code:r.status,last_success_at:r.ok?new Date().toISOString():hook.last_success_at,last_failure_at:r.ok?hook.last_failure_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',hook.id);return{ok:r.ok,status:r.status,duration_ms:Date.now()-started,response_body:body}}catch(e){await s.from('pixwiki_webhooks').update({last_failure_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',hook.id);return{ok:false,status:null,duration_ms:Date.now()-started,error:e instanceof Error?e.message:'delivery_failed'}}}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers});const s=createClient(SUPABASE_URL,SERVICE_ROLE)
 try{
  const user=await getUser(s,req);if(!user)return new Response(JSON.stringify({error:'not_authenticated'}),{status:401,headers});await requireFeature(s,user.id,'api');const body=await req.json().catch(()=>({})),action=String(body?.action||'')
  if(action==='list_keys'){const{data,error}=await s.from('pixwiki_api_keys').select('id,name,key_prefix,last_used_at,revoked_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return new Response(JSON.stringify({ok:true,keys:data||[]}),{headers})}
  if(action==='create_key'){const name=String(body?.name||'Chave API').trim().slice(0,80);if(!name)return new Response(JSON.stringify({error:'name_required'}),{status:400,headers});const raw=randomSecret('pw_live_'),hash=await sha256(raw),prefix=raw.slice(0,18);const{data,error}=await s.from('pixwiki_api_keys').insert({user_id:user.id,name,key_prefix:prefix,key_hash:hash}).select('id,name,key_prefix,created_at').single();if(error)throw error;return new Response(JSON.stringify({ok:true,key:data,secret:raw,show_once:true}),{headers})}
  if(action==='revoke_key'){const id=String(body?.key_id||'');const{error}=await s.from('pixwiki_api_keys').update({revoked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)throw error;return new Response(JSON.stringify({ok:true}),{headers})}
  if(action==='list_webhooks'){const{data:hooks,error}=await s.from('pixwiki_webhooks').select('id,company_id,name,url,is_active,event_types,last_success_at,last_failure_at,last_status_code,created_at,updated_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;const ids=(hooks||[]).map((h:any)=>h.id);let deliveries:any[]=[];if(ids.length){const res=await s.from('pixwiki_webhook_deliveries').select('webhook_id,status,attempt_count,created_at,delivered_at,response_status').in('webhook_id',ids).order('created_at',{ascending:false}).limit(100);deliveries=res.data||[]}return new Response(JSON.stringify({ok:true,webhooks:hooks||[],deliveries}),{headers})}
  if(action==='create_webhook'){const name=String(body?.name||'Webhook').trim().slice(0,80),url=validateWebhookUrl(String(body?.url||'').trim()),companyId=body?.company_id?String(body.company_id):null;if(!(await companyAllowed(s,user.id,companyId)))return new Response(JSON.stringify({error:'company_not_allowed'}),{status:403,headers});const{data:hook,error}=await s.from('pixwiki_webhooks').insert({user_id:user.id,company_id:companyId,name,url,event_types:['pix.received'],is_active:true}).select('id,company_id,name,url,is_active,event_types,created_at').single();if(error)throw error;const secret=randomSecret('whsec_');const{error:se}=await s.from('pixwiki_webhook_secrets').insert({webhook_id:hook.id,signing_secret:secret});if(se){await s.from('pixwiki_webhooks').delete().eq('id',hook.id);throw se}return new Response(JSON.stringify({ok:true,webhook:hook,signing_secret:secret,show_once:true}),{headers})}
  if(action==='update_webhook'){const id=String(body?.webhook_id||'');const{data:existing}=await s.from('pixwiki_webhooks').select('id').eq('id',id).eq('user_id',user.id).maybeSingle();if(!existing)return new Response(JSON.stringify({error:'webhook_not_found'}),{status:404,headers});const update:any={updated_at:new Date().toISOString()};if(body?.url!==undefined)update.url=validateWebhookUrl(String(body.url).trim());if(body?.name!==undefined)update.name=String(body.name).trim().slice(0,80)||'Webhook';if(body?.is_active!==undefined)update.is_active=body.is_active===true;if(body?.company_id!==undefined){const c=body.company_id?String(body.company_id):null;if(!(await companyAllowed(s,user.id,c)))return new Response(JSON.stringify({error:'company_not_allowed'}),{status:403,headers});update.company_id=c}const{data,error}=await s.from('pixwiki_webhooks').update(update).eq('id',id).eq('user_id',user.id).select('id,company_id,name,url,is_active,event_types,last_success_at,last_failure_at,last_status_code,updated_at').single();if(error)throw error;return new Response(JSON.stringify({ok:true,webhook:data}),{headers})}
  if(action==='delete_webhook'){const{error}=await s.from('pixwiki_webhooks').delete().eq('id',String(body?.webhook_id||'')).eq('user_id',user.id);if(error)throw error;return new Response(JSON.stringify({ok:true}),{headers})}
  if(action==='rotate_webhook_secret'){const id=String(body?.webhook_id||'');const{data:h}=await s.from('pixwiki_webhooks').select('id').eq('id',id).eq('user_id',user.id).maybeSingle();if(!h)return new Response(JSON.stringify({error:'webhook_not_found'}),{status:404,headers});const secret=randomSecret('whsec_');const{error}=await s.from('pixwiki_webhook_secrets').update({signing_secret:secret,rotated_at:new Date().toISOString()}).eq('webhook_id',id);if(error)throw error;return new Response(JSON.stringify({ok:true,signing_secret:secret,show_once:true}),{headers})}
  if(action==='test_webhook'){const id=String(body?.webhook_id||'');const[{data:h},{data:sec}]=await Promise.all([s.from('pixwiki_webhooks').select('*').eq('id',id).eq('user_id',user.id).maybeSingle(),s.from('pixwiki_webhook_secrets').select('signing_secret').eq('webhook_id',id).maybeSingle()]);if(!h||!sec?.signing_secret)return new Response(JSON.stringify({error:'webhook_not_found'}),{status:404,headers});const result=await sendTestWebhook(s,h,String(sec.signing_secret));return new Response(JSON.stringify({ok:result.ok,result}),{status:result.ok?200:502,headers})}
  return new Response(JSON.stringify({error:'invalid_action'}),{status:400,headers})
 }catch(e){const m=e instanceof Error?e.message:'internal_error';console.error('[pixwiki-api-admin]',m);return new Response(JSON.stringify({error:m}),{status:m==='pix_pro_required'?403:m.includes('webhook')||m.includes('private_')||m.includes('limit_reached')?400:500,headers})}
})
