const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const company = '11111111-1111-4111-8111-111111111111';
const other = '22222222-2222-4222-8222-222222222222';
const appointmentId = '33333333-3333-4333-8333-333333333333';
const key = 'mock-service-only-secret';
const day = new Date(Date.now() + 10 * 86400000).toISOString().slice(0,10);
const start = `${day}T10:00:00-03:00`, end = `${day}T11:00:00-03:00`;
let state, calls, queries, logs, handlers, modules, cases = 0, ipCounter = 0, clock = Date.now();
class Clock extends Date { constructor(...args) { super(...(args.length ? args : [clock])); } static now() { return clock; } }
function reset() {
  clock = Date.now(); calls = []; queries = []; logs = []; handlers = {}; modules = new Map();
  state = { companies: [{id:company,is_active:true,is_public:true,user_id:'owner'}], funcionaria_company_settings: [],
    google_accounts: [{company_id:company,is_active:true,scopes:['https://www.googleapis.com/auth/calendar'],access_token:'private-google-token',expires_at:new Date(clock+3600000).toISOString()}],
    customer_appointments: [{id:appointmentId,company_id:company,customer_name:'João Completo',customer_email:'secret@example.test',customer_phone:'secret-phone',appointment_date:start,appointment_end:end,google_event_id:'database-google-id',status:'scheduled',original_date:null,updated_at:null,service_type:'Consulta'}],
    interaction_history: [], errors:{}, deleteStatus:204, patchStatus:200, readStatus:200, refreshStatus:200, edgeStatus:200, edgeResult:{success:true,events:[]},
    events:[{id:'secret-event-id',summary:'secret-summary',description:'secret-description',attendees:[{email:'secret@example.test'}],start:{dateTime:start},end:{dateTime:end}}], actor:'owner', extracted:{nome:'João Completo',data:day,hora:'10:00',nova_data:day,nova_hora:'12:00'},nextPage:false };
}
const admin = { auth:{ async getUser(token) { return {data:{user:token==='owner-token'?{id:'owner'}:token==='outsider-token'?{id:'outsider'}:null}}; } }, from(table) {
  const q={table,filters:[],limit:Infinity}; queries.push(q);
  const chain={ select(){return this;},eq(k,v){q.filters.push(['eq',k,v]);return this;},is(k,v){q.filters.push(['eq',k,v]);return this;},neq(k,v){q.filters.push(['neq',k,v]);return this;},in(k,v){q.filters.push(['in',k,v]);return this;},gte(k,v){q.filters.push(['gte',k,v]);return this;},gt(k,v){q.filters.push(['gt',k,v]);return this;},lt(k,v){q.filters.push(['lt',k,v]);return this;},order(){return this;},limit(v){q.limit=v;return this;},maybeSingle(){q.single=true;return this;},update(v){q.update=v;return this;},insert(v){q.insert=v;return this;},then(resolve,reject){
    if(state.errors[table] || q.update && state.updateError) return Promise.resolve({data:null,error:{message:'secret-db-error'}}).then(resolve,reject);
    let rows=(state[table]||[]).filter(row=>q.filters.every(([op,k,v])=>op==='eq'?row[k]===v:op==='neq'?row[k]!==v:op==='in'?v.includes(row[k]):op==='gte'?Date.parse(row[k])>=Date.parse(v):op==='gt'?Date.parse(row[k])>Date.parse(v):op==='lt'?Date.parse(row[k])<Date.parse(v):false));
    rows=rows.slice(0,q.limit); if(q.insert){(state[table] ||= []).push(q.insert);rows=[q.insert];} if(q.update) rows.forEach(row=>Object.assign(row,q.update));
    return Promise.resolve({data:q.single?rows[0]||null:rows,error:null}).then(resolve,reject);
  }};return chain;
}};
async function fakeFetch(url,options={}) {
  url=String(url);const body=options.body?JSON.parse(options.body):null;calls.push({url,...options,body});
  if(url.includes('openai.com')) return Response.json({choices:[{message:{content:JSON.stringify(state.extracted)}}]});
  if(url.includes('/google-refresh-token')) {if(state.refreshStatus===200){state.google_accounts[0].access_token='updated-private-token';state.google_accounts[0].expires_at=new Date(clock+3600000).toISOString();}return Response.json({success:state.refreshStatus===200,secret:'private-refresh-payload'},{status:state.refreshStatus});}
  if(url.includes('/functions/v1/')) return Response.json(state.edgeResult,{status:state.edgeStatus});
  if(options.method==='DELETE') return new Response(state.deleteStatus===204?null:JSON.stringify({secret:'private-google-error'}),{status:state.deleteStatus});
  if(options.method==='PATCH') return Response.json({secret:'private-google-payload'},{status:state.patchStatus});
  return Response.json(state.readStatus===200?{items:state.events,...(state.nextPage?{nextPageToken:'next'}:{})}:{secret:'private-google-error'},{status:state.readStatus});
}
function load(relative) {
  const file=path.resolve(root,relative);if(modules.has(file))return modules.get(file);
  const module={exports:{}};modules.set(file,module.exports);
  const source=fs.readFileSync(file,'utf8');
  const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});assert.equal(compiled.diagnostics.length,0,file);
  const localRequire=name=>{
    if(name==='server-only')return {};
    if(name==='next/server')return {NextResponse:{json:(value,options={})=>Response.json(value,options)}};
    if(name.includes('supabase-js'))return {createClient:()=>admin};
    if(name==='@/lib/supabase-admin')return {createAdminClient:()=>admin};
    if(name==='https://deno.land/std@0.168.0/http/server.ts')return {serve:handler=>handlers[file]=handler};
    if(name.startsWith('node:'))return require(name);
    const resolved=name.startsWith('@/')?path.resolve(root,name.slice(2)):path.resolve(path.dirname(file),name);
    return load(path.relative(root,resolved.endsWith('.ts')?resolved:resolved+'.ts'));
  };
  vm.runInNewContext(compiled.outputText,{require:localRequire,exports:module.exports,module,Buffer,process:{env:{APPOINTMENT_ACTION_SECRET:key,SUPABASE_SERVICE_ROLE_KEY:key,NEXT_PUBLIC_SUPABASE_URL:'https://supabase.test'}},Deno:{env:{get:name=>name==='SUPABASE_URL'?'https://supabase.test':name==='OPENAI_API_KEY'?'mock-openai':key},serve:handler=>handlers[file]=handler},Date:Clock,Intl,TextEncoder,TextDecoder,Uint8Array,URL,URLSearchParams,Request,Response,AbortSignal,fetch:fakeFetch,console:{warn:(...a)=>logs.push(a.join(' ')),error:(...a)=>logs.push(a.join(' ')),log:()=>{}}},{filename:file});
  return module.exports;
}
async function request(file,input,options={}) {
  load(file);const fn=handlers[path.resolve(root,file)]||load(file).POST;
  const req=new Request('https://app.test/api/test',{method:options.method||'POST',headers:{'content-type':'application/json',host:'app.test','x-forwarded-for':String(++ipCounter),...(options.edge?{Authorization:'Bearer '+key}:{}),...options.headers},...(options.method&&options.method!=='POST'?{}:{body:JSON.stringify(input)})});
  const response=await fn(req),result=await response.json();if(!file.includes('meta-agenda')) assert.equal(response.headers.get('cache-control'),'no-store');
  const serialized=JSON.stringify(result);for(const secret of ['private-google-token','updated-private-token','private-google-error','private-refresh-payload',...(file.includes('/public/') ? ['secret@example.test','secret-phone'] : [])])assert.ok(!serialized.includes(secret),serialized);
  return {status:response.status,result};
}
const list='supabase/functions/listar-eventos-google-v2/index.ts',actions='supabase/functions/appointment-actions-v2/index.ts';
const search='app/api/public/appointments/search/route.ts',actionRoute='app/api/public/appointments/action/route.ts',availability='app/api/public/calendar/availability/route.ts',adminRoute='app/api/calendar/events/route.ts';
const listing={company_id:company,time_min:start,time_max:end},acting={company_id:company,appointment_id:appointmentId,action:'confirm'};
async function test(name,fn){reset();await fn();cases++;console.log('PASS '+name);}
(async()=>{
 await test('list auth exact + methods',async()=>{for(const token of [undefined,'anon','user-jwt']) assert.equal((await request(list,listing,{headers:token?{Authorization:'Bearer '+token}:{}})).status,401);assert.equal((await request(list,listing,{edge:true,method:'GET'})).status,405);assert.equal((await request(list,listing,{edge:true})).status,200);});
 await test('list strict company/window/max/results',async()=>{for(const input of [{...listing,company_id:'bad'},{...listing,time_min:end,time_max:start},{...listing,time_max:'2099-01-01T00:00:00Z'},{...listing,max_results:0},{...listing,max_results:1.5},{...listing,to:'bad'},{...listing,time_min:'2026-02-30T00:00:00Z'}])assert.equal((await request(list,input,{edge:true})).status,400);await request(list,{...listing,max_results:999},{edge:true});assert.ok(calls.at(-1).url.includes('maxResults=250'));});
 await test('list inactive/missing company/account/scopes',async()=>{state.companies=[];assert.equal((await request(list,listing,{edge:true})).status,404);reset();state.companies[0].is_active=false;assert.equal((await request(list,listing,{edge:true})).status,404);reset();state.google_accounts=[];assert.equal((await request(list,listing,{edge:true})).result.error,'google_account_unavailable');reset();state.google_accounts[0].scopes=[];assert.equal((await request(list,listing,{edge:true})).status,409);});
 await test('list refresh exact auth/requery/read sanitized',async()=>{state.google_accounts[0].expires_at=new Date(clock-1000).toISOString();assert.equal((await request(list,listing,{edge:true})).status,200);assert.equal(calls[0].headers.Authorization,'Bearer '+key);assert.equal(calls[0].headers.apikey,key);assert.equal(calls[1].headers.Authorization,'Bearer updated-private-token');assert.equal(queries.filter(q=>q.table==='google_accounts').length,2);reset();state.readStatus=500;assert.equal((await request(list,listing,{edge:true})).result.error,'calendar_read_failed');});
 await test('actions auth/ID/company/status',async()=>{assert.equal((await request(actions,acting)).status,401);assert.equal((await request(actions,{...acting,appointment_id:undefined},{edge:true})).status,400);assert.equal((await request(actions,{...acting,company_id:other},{edge:true})).status,404);state.customer_appointments=[];assert.equal((await request(actions,acting,{edge:true})).status,404);reset();state.customer_appointments[0].status='completed';assert.equal((await request(actions,acting,{edge:true})).status,409);for(const extra of ['event_id','google_event_id','customer_email','message'])assert.equal((await request(actions,{...acting,[extra]:'x'},{edge:true})).status,400);});
 await test('confirm persists + repeated idempotent + history',async()=>{assert.equal((await request(actions,acting,{edge:true})).status,200);assert.equal(state.customer_appointments[0].status,'confirmed');assert.ok(state.customer_appointments[0].confirmed_at);assert.equal(state.interaction_history.length,1);assert.equal((await request(actions,acting,{edge:true})).status,200);assert.equal(queries.filter(q=>q.update).length,1);assert.equal(calls.length,0);});
 await test('cancel DB event + 404 + idempotent',async()=>{state.deleteStatus=404;assert.equal((await request(actions,{...acting,action:'cancel'},{edge:true})).status,200);assert.ok(calls[0].url.endsWith('/database-google-id'));assert.equal(state.customer_appointments[0].status,'cancelled');await request(actions,{...acting,action:'cancel'},{edge:true});assert.equal(calls.length,1);});
 await test('cancel Google error does not mutate',async()=>{state.deleteStatus=500;const result=await request(actions,{...acting,action:'cancel'},{edge:true});assert.equal(result.status,502);assert.equal(state.customer_appointments[0].status,'scheduled');assert.equal(queries.filter(q=>q.update).length,0);});
 const moved={...acting,action:'reschedule',new_start:`${day}T12:00:00-03:00`,new_end:`${day}T13:00:00-03:00`};
 await test('reschedule correct overlap/excludes self + boundaries',async()=>{state.customer_appointments.push({...state.customer_appointments[0],id:other,appointment_date:`${day}T11:30:00-03:00`,appointment_end:`${day}T12:30:00-03:00`});assert.equal((await request(actions,moved,{edge:true})).result.error,'slot_unavailable');assert.equal(calls.length,0);state.customer_appointments.pop();assert.equal((await request(actions,{...acting,action:'reschedule',new_start:start,new_end:end},{edge:true})).status,200);const overlap=queries.find(q=>q.filters.some(f=>f[0]==='neq'));assert.ok(overlap.filters.some(f=>f[0]==='lt'&&f[1]==='appointment_date'));assert.ok(overlap.filters.some(f=>f[0]==='gt'&&f[1]==='appointment_end'));});
 await test('reschedule original_date preservation + invalid dates',async()=>{await request(actions,moved,{edge:true});assert.equal(state.customer_appointments[0].original_date,start);assert.equal(state.customer_appointments[0].status,'rescheduled');const original=state.customer_appointments[0].original_date;await request(actions,{...moved,new_start:`${day}T14:00:00-03:00`,new_end:`${day}T15:00:00-03:00`},{edge:true});assert.equal(state.customer_appointments[0].original_date,original);for(const input of [{...moved,new_start:'2000-01-01T00:00:00Z'},{...moved,new_end:moved.new_start},{...moved,new_end:'2099-01-01T00:00:00Z'},{...moved,new_start:`${day}T12:00:00`}])assert.equal((await request(actions,input,{edge:true})).status,400);});
 await test('PATCH failure unchanged + DB failure rollback',async()=>{state.patchStatus=500;assert.equal((await request(actions,moved,{edge:true})).status,502);assert.equal(state.customer_appointments[0].appointment_date,start);reset();state.updateError=true;assert.equal((await request(actions,moved,{edge:true})).status,503);assert.equal(calls.filter(c=>c.method==='PATCH').length,2);assert.equal(calls.at(-1).body.start.dateTime,start);assert.equal(state.customer_appointments[0].status,'scheduled');});
 await test('search strict date+identifier + exact name/ambiguity',async()=>{const input={company_id:company,action:'confirm',date:day};for(const bad of [{...input,date:undefined},input,{...input,name:'Jo'},{...input,date:'2026-02-30',time:'10:00'}])assert.equal((await request(search,bad)).status,400);assert.equal((await request(search,{...input,name:'João'})).status,404);state.customer_appointments.push({...state.customer_appointments[0],id:other});const result=await request(search,{...input,time:'10:00'});assert.equal(result.status,409);assert.equal(result.result.reason,'appointment_ambiguous');assert.ok(!JSON.stringify(result.result).includes('appointment_id'));});
 await test('search only safe summary + capability',async()=>{const result=await request(search,{company_id:company,action:'confirm',date:day,name:'  JOÃO   COMPLETO '});assert.equal(result.status,200);assert.equal(result.result.appointment_id,appointmentId);assert.deepEqual(Object.keys(result.result).sort(),['appointment_id','capability','date','service_type','time']);assert.ok(!result.result.capability.includes(key));assert.ok(!JSON.stringify(result.result).includes('database-google-id'));});
 await test('capability company/appointment/action/expiry/signature',async()=>{const cap=load('lib/appointment-capability.ts');const token=cap.signAppointmentCapability(company,appointmentId,'confirm');assert.equal(cap.verifyAppointmentCapability(token,company,appointmentId,'confirm'),true);for(const args of [[other,appointmentId,'confirm'],[company,other,'confirm'],[company,appointmentId,'cancel']])assert.equal(cap.verifyAppointmentCapability(token,...args),false);assert.equal(cap.verifyAppointmentCapability(token+'a',company,appointmentId,'confirm'),false);clock+=1800001;assert.equal(cap.verifyAppointmentCapability(token,company,appointmentId,'confirm'),false);});
 await test('public action requires exact capability + whitelist + service auth',async()=>{const cap=load('lib/appointment-capability.ts');const token=cap.signAppointmentCapability(company,appointmentId,'confirm');assert.equal((await request(actionRoute,acting)).status,403);assert.equal((await request(actionRoute,{...acting,action:'cancel',capability:token})).status,403);assert.equal((await request(actionRoute,{...acting,capability:token,google_event_id:'x'})).status,400);assert.equal((await request(actionRoute,{...acting,capability:token})).status,200);assert.ok(calls.at(-1).url.endsWith('/appointment-actions-v2'));assert.equal(calls.at(-1).headers.Authorization,'Bearer '+key);assert.equal(calls.at(-1).body.appointment_id,appointmentId);assert.ok(!calls.at(-1).body.capability);});
 await test('public availability strips details + rejects truncation/origin/window',async()=>{state.edgeResult.events=state.events;const result=await request(availability,listing);assert.equal(result.status,200);assert.deepEqual(Object.keys(result.result[0]).sort(),['all_day','end','start']);assert.ok(!JSON.stringify(result.result).includes('secret'));state.edgeResult.truncated=true;assert.equal((await request(availability,listing)).status,409);assert.equal((await request(availability,listing,{headers:{Origin:'https://external.test'}})).status,403);assert.equal((await request(availability,{...listing,time_max:new Date(Date.parse(start)+61*86400000).toISOString()})).status,400);});
 await test('public/private/FuncionarIA active + cross company denial',async()=>{state.companies[0].is_public=false;assert.equal((await request(availability,listing)).status,403);assert.equal((await request(availability,listing,{headers:{Authorization:'Bearer outsider-token'}})).status,403);assert.equal((await request(availability,listing,{headers:{Authorization:'Bearer owner-token'}})).status,200);state.funcionaria_company_settings=[{company_id:company}];assert.equal((await request(availability,listing)).status,200);state.companies[0].is_active=false;assert.equal((await request(availability,listing)).status,404);});
 await test('admin owner/admin/staff only, not cliente/totem/expired/other',async()=>{assert.equal((await request(adminRoute,listing)).status,401);assert.equal((await request(adminRoute,listing,{headers:{Authorization:'Bearer owner-token'}})).status,200);state.company_admins=[{company_id:company,user_id:'outsider',role:'admin'}];assert.equal((await request(adminRoute,listing,{headers:{Authorization:'Bearer outsider-token'}})).status,200);state.company_admins=[];
  for(const type of ['cliente','totem','gerente','administrador','frentista','caixa','atendente','colaborador']){state.profile_sessions=[{token:'profile',company_id:company,profile_id:other,expires_at:new Date(clock+10000).toISOString()}];state.company_profiles=[{id:other,company_id:company,tipo:type,is_active:true}];assert.equal((await request(adminRoute,{...listing,profile_tokens:['profile']})).status,['cliente','totem'].includes(type)?403:200);}
  state.profile_sessions[0].expires_at=new Date(clock-1).toISOString();assert.equal((await request(adminRoute,{...listing,profile_tokens:['profile']})).status,403);state.profile_sessions[0].company_id=other;assert.equal((await request(adminRoute,{...listing,profile_tokens:['profile']})).status,403);
 });
 await test('search rate limit + safe errors/other company',async()=>{const module=load(search);let last;for(let i=0;i<21;i++){last=await module.POST(new Request('https://app.test/api/test',{method:'POST',headers:{host:'app.test','x-forwarded-for':'same-ip'},body:JSON.stringify({company_id:company,action:'confirm',date:day,time:'10:00'})}));}assert.equal(last.status,429);assert.ok(Number(last.headers.get('retry-after'))>0);assert.equal((await request(search,{company_id:other,action:'confirm',date:day,time:'10:00'})).status,404);});
 await test('Meta missing info + ambiguity no mutation; confirm only after success',async()=>{
  const meta='supabase/functions/meta-agenda/index.ts';const input={msg:'confirmar presença',msgLower:'confirmar presença',connection:{agendar_enabled:true},companyId:company,company:{}};
  state.extracted={};let result=await request(meta,input,{edge:true});assert.equal(result.result.creditsUsed,0);assert.ok(!calls.some(c=>c.url.endsWith('/appointment-actions-v2')));
  reset();state.customer_appointments.push({...state.customer_appointments[0],id:other});result=await request(meta,{...input,msg:'cancelar agendamento',msgLower:'cancelar agendamento'},{edge:true});assert.equal(result.result.creditsUsed,0);assert.ok(!calls.some(c=>c.url.endsWith('/appointment-actions-v2')));
  reset();state.edgeResult={success:false,error:'private-google-error'};state.edgeStatus=502;result=await request(meta,input,{edge:true});assert.equal(result.result.creditsUsed,0);assert.ok(!result.result.responseText.includes('Presença confirmada'));
  reset();result=await request(meta,input,{edge:true});assert.equal(result.result.creditsUsed,1);assert.ok(result.result.responseText.includes('Presença confirmada'));assert.equal(calls.at(-1).body.appointment_id,appointmentId);
 });
 await test('modals persist internal IDs and safe search',async()=>{for(const [file,action] of [['ConfirmPresenceModal.tsx','confirm'],['CancelAppointmentModal.tsx','cancel'],['RescheduleModal.tsx','reschedule']]){const source=fs.readFileSync(path.join(root,'components/assistant',file),'utf8');assert.ok(source.includes('searchPublicAppointment'));assert.ok(source.includes('actOnPublicAppointment'));assert.ok(source.includes('appointment_id: selectedEvent.appointment_id'));assert.ok(source.includes(`action: '${action}'`));assert.ok(!source.includes('event_id:'));assert.ok(!source.includes('NEXT_PUBLIC_SUPABASE_ANON_KEY'));}});
 await test('guardrails reject registry email edge + exact legacy, allow V2 server',async()=>{
  const registry=path.join(root,'lib/functions-registry.ts'),original=fs.readFileSync(registry,'utf8');
  const entry=/enviar_email:\s*\{[\s\S]*?edgeFunction: undefined/;assert.ok(entry.test(original));
  try{for(const name of ['enviar-email-google','enviar-email-google-v2']){fs.writeFileSync(registry,original.replace(entry,match=>match.replace('edgeFunction: undefined',`edgeFunction: '${name}'`)));assert.equal(spawnSync(process.execPath,['scripts/check-email-edge-boundary.mjs'],{cwd:root}).status,1);}}finally{fs.writeFileSync(registry,original);}
  const probe=path.join(root,'lib',`.calendar-test-${process.pid}.ts`);
  try{for(const [text,expected] of [["export const x='listar-eventos-google';",1],["export const x='cancelar-agendamento';",1],["export const x='reagendar-compromisso';",1],["export const x='listar-eventos-google-v2';",0],["'use client'; export const x='appointment-actions-v2';",1],["export const x='criar-evento-calendario';",1]]){fs.writeFileSync(probe,text);assert.equal(spawnSync(process.execPath,['scripts/check-calendar-edge-boundary.mjs'],{cwd:root}).status,expected,text);}}finally{fs.rmSync(probe,{force:true});}
 });
 assert.ok(!logs.join(' ').includes('private-google-token'));
 console.log(`PASS: ${cases} calendar/security test groups; no real Google/Supabase/OpenAI calls.`);
})().catch(error=>{console.error(error);process.exitCode=1});
