const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
const env={NEXT_PUBLIC_SUPABASE_URL:'https://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'legacy-jwt'};
let sdkCalls=[];
function load(file){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,process:{env},console:{log(){assert.fail('secret logging');},warn(){assert.fail('secret logging');},error(){assert.fail('secret logging');}},require:name=>name==='server-only'?{}:name==='@supabase/supabase-js'?{createClient:(...args)=>{sdkCalls.push(args);return {};}}:load('lib/supabase-server-key.ts')});return exports;}
const selector=load('lib/supabase-server-key.ts'),admin=load('lib/supabase-admin.ts'),headers=load('lib/internal-service-headers.ts');
assert.equal(selector.getSupabaseServerKey(),'legacy-jwt');admin.createAdminClient();assert.deepEqual(sdkCalls.pop(),[env.NEXT_PUBLIC_SUPABASE_URL,'legacy-jwt']);assert.equal(headers.internalServiceHeaders().Authorization,'Bearer legacy-jwt');
env.SUPABASE_SECRET_KEY='sb_secret_valid-KEY_123';assert.equal(selector.getSupabaseServerKey(),env.SUPABASE_SECRET_KEY);admin.createAdminClient();assert.deepEqual(sdkCalls.pop(),[env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SECRET_KEY]);assert.equal(headers.internalServiceHeaders().apikey,env.SUPABASE_SECRET_KEY);assert.equal(headers.internalServiceHeaders().Authorization,undefined);
for(const value of ['', ' ', 'sb_secret_', 'sb_publishable_test', 'sb_secret_bad\n', 'sb_secret_bad/']){env.SUPABASE_SECRET_KEY=value;for(const fn of [selector.getSupabaseServerKey,admin.createAdminClient,headers.internalServiceHeaders]){assert.throws(fn,error=>error.message==='supabase_server_key_unavailable');}assert.equal(sdkCalls.length,0);}
delete env.SUPABASE_SECRET_KEY;delete env.SUPABASE_SERVICE_ROLE_KEY;assert.throws(selector.getSupabaseServerKey,/supabase_server_key_unavailable/);
console.log('Server key selection/admin: modern priority, legacy fallback, fail closed, no logs: PASS');
