'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CreditCard, Loader2, QrCode, ReceiptText } from 'lucide-react';
import { createClient } from '@/lib/supabase-browser';

export default function FuncionarIACashierPanel({companyId}:{companyId:string}){
 const supabase=useMemo(()=>createClient(),[]); const [info,setInfo]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const [{data:c},{data:p}]=await Promise.all([supabase.from('companies').select('mp_access_token,mp_terminal_id,infinitepay_handle').eq('id',companyId).maybeSingle(),supabase.from('pix_payment_preferences').select('mode').eq('company_id',companyId).eq('product','funcionaria').maybeSingle()]);if(alive){setInfo({mp:!!c?.mp_access_token&&!!c?.mp_terminal_id,infinite:!!c?.infinitepay_handle,pix:p?.mode||'free'});setLoading(false)}})();return()=>{alive=false}},[companyId,supabase]);
 return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Link href="/nova" className="rounded-3xl border border-violet-100 bg-white p-5 shadow-sm"><QrCode className="h-6 w-6 text-[#6D28D9]"/><div className="mt-4 font-black">Nova cobrança</div><p className="mt-1 text-sm text-slate-500">Monte uma venda e gere código/QR para o cliente.</p></Link><Link href="/terminal" className="rounded-3xl border border-violet-100 bg-white p-5 shadow-sm"><CreditCard className="h-6 w-6 text-[#6D28D9]"/><div className="mt-4 font-black">Abrir terminal</div><p className="mt-1 text-sm text-slate-500">Receba Pix, cartão ou dinheiro assistido.</p></Link><Link href="/dashboard/recebimentos" className="rounded-3xl border border-violet-100 bg-white p-5 shadow-sm"><ReceiptText className="h-6 w-6 text-[#6D28D9]"/><div className="mt-4 font-black">Recebimentos</div><p className="mt-1 text-sm text-slate-500">Confirme dinheiro e acesse comprovantes.</p></Link></div><div className="rounded-3xl border border-slate-200 bg-white p-5">{loading?<Loader2 className="h-5 w-5 animate-spin text-slate-400"/>:<><div className="text-xs font-black uppercase tracking-wide text-slate-400">Configuração herdada da minhAi</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Status label="Pix" value={info?.pix==='mercadopago'?'Mercado Pago':'Pix direto'} ok/><Status label="Mercado Pago Point" value={info?.mp?'Configurado':'Não configurado'} ok={info?.mp}/><Status label="InfinitePay" value={info?.infinite?'Configurada':'Não configurada'} ok={info?.infinite}/></div><p className="mt-4 text-xs text-slate-400">A FuncionarIA reutiliza os gateways que já estão configurados para a empresa. Pagamentos do caixa não consomem créditos de IA.</p></>}</div></div>
}
function Status({label,value,ok}:{label:string,value:string,ok:boolean}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-400">{label}</div><div className={`mt-1 text-sm font-black ${ok?'text-lime-700':'text-slate-500'}`}>{value}</div></div>}
