'use client';

import { useEffect, useMemo, useState } from 'react';
import { Edit3, Loader2, PackagePlus, Save, Trash2, X } from 'lucide-react';
import { criarProduto, atualizarProduto, excluirProduto, listarProdutos, type ProdutoVenda } from '@/lib/produtos-venda';
import { formatarBRL } from '@/lib/funcionaria';

type Form = { id?: string; nome: string; preco_venda: string; estoque_atual: string; estoque_minimo: string; categoria: string; ean: string; controla_estoque: boolean; is_active: boolean };
const empty: Form = { nome: '', preco_venda: '', estoque_atual: '0', estoque_minimo: '0', categoria: '', ean: '', controla_estoque: true, is_active: true };

export default function FuncionarIAProductsPanel({ companyId }: { companyId: string }) {
  const [items, setItems] = useState<ProdutoVenda[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<Form | null>(null); const [search, setSearch] = useState(''); const [notice, setNotice] = useState<string | null>(null);
  async function load() { setLoading(true); try { setItems(await listarProdutos(companyId)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [companyId]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => items.filter(i => `${i.nome} ${i.categoria || ''} ${i.ean || ''}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  function edit(p: ProdutoVenda) { setForm({ id:p.id,nome:p.nome,preco_venda:String(p.preco_venda),estoque_atual:String(p.estoque_atual),estoque_minimo:String(p.estoque_minimo),categoria:p.categoria||'',ean:p.ean||'',controla_estoque:p.controla_estoque,is_active:p.is_active }); }
  async function save() { if (!form?.nome.trim() || Number(form.preco_venda) <= 0) return; setSaving(true); setNotice(null); try { const payload:any={ company_id:companyId,nome:form.nome.trim(),preco_venda:Number(form.preco_venda||0),estoque_atual:Number(form.estoque_atual||0),estoque_minimo:Number(form.estoque_minimo||0),categoria:form.categoria.trim()||undefined,ean:form.ean.trim()||undefined,controla_estoque:form.controla_estoque,is_active:form.is_active,unidade:'un' }; if(form.id) await atualizarProduto(form.id,payload); else await criarProduto(payload); setForm(null); await load(); setNotice('Produto salvo.'); } catch(e:any){setNotice(e?.message||'Erro ao salvar.')} finally{setSaving(false)} }
  async function remove(id:string){ if(!window.confirm('Excluir este produto?')) return; await excluirProduto(id); await load(); }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto, categoria ou EAN" className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-semibold outline-none sm:max-w-md"/><button onClick={()=>setForm({...empty})} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#6D28D9] px-4 py-3 text-sm font-black text-white"><PackagePlus className="h-4 w-4"/>Novo produto</button></div>
    {notice&&<div className="rounded-2xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-600">{notice}</div>}
    {loading?<div className="py-12 text-center text-sm font-bold text-slate-400"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin"/>Carregando…</div>:<div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{filtered.map(p=><div key={p.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><div className="font-black">{p.nome}</div><div className="mt-1 text-xs font-semibold text-slate-400">{p.categoria||'Sem categoria'}{p.ean?` • EAN ${p.ean}`:''}</div></div><div className="sm:text-right"><div className="font-black">{formatarBRL(p.preco_venda)}</div><div className="text-xs text-slate-400">Estoque: {p.controla_estoque?p.estoque_atual:'não controlado'}</div></div><div className="flex gap-2 sm:justify-end"><button onClick={()=>edit(p)} className="rounded-xl border border-slate-200 p-2 text-slate-600"><Edit3 className="h-4 w-4"/></button><button onClick={()=>void remove(p.id)} className="rounded-xl border border-red-100 p-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div></div>)}{!filtered.length&&<div className="p-10 text-center text-sm font-bold text-slate-400">Nenhum produto encontrado.</div>}</div></div>}
    {form&&<div className="fixed inset-0 z-[500] flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-black">{form.id?'Editar produto':'Novo produto'}</h2><button onClick={()=>setForm(null)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-black">Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5 font-semibold"/></label><label className="text-sm font-black">Preço<input type="number" step="0.01" value={form.preco_venda} onChange={e=>setForm({...form,preco_venda:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-black">Categoria<input value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-black">Estoque<input type="number" value={form.estoque_atual} onChange={e=>setForm({...form,estoque_atual:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-black">Estoque mínimo<input type="number" value={form.estoque_minimo} onChange={e=>setForm({...form,estoque_minimo:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="sm:col-span-2 text-sm font-black">EAN / código de barras<input value={form.ean} onChange={e=>setForm({...form,ean:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label></div><button onClick={()=>void save()} disabled={saving} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#6D28D9] py-3 font-black text-white">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar</button></div></div>}
  </div>;
}
