'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Check, Loader2, RefreshCcw } from 'lucide-react';
import { createClient } from '@/lib/supabase-browser';
import { formatarBRL } from '@/lib/funcionaria';

export default function FuncionarIAReceivablesPanel({companyId,slug}:{companyId:string;slug:string}){
 const supabase=useMemo(()=>createClient(),[]); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
 async function load(){setLoading(true);const {data,error}=await supabase.rpc('funcionaria_receivables',{p_company_id:companyId,p_limit:80});if(error)setNotice(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[companyId]); // eslint-disable-line react-hooks/exhaustive-deps
 async function confirm(code:string){setBusy(code);setNotice(null);const {error}=await supabase.rpc('funcionaria_confirm_cash',{p_codigo:code});if(error)setNotice(error.message);else setNotice(`Pagamento ${code} confirmado em dinheiro.`);setBusy(null);await load()}
 return <div className="space-y-4">{notice&&<div className="rounded-2xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-600">{notice}</div>}<div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b p-4"><div className="font-black">Recebimentos recentes</div><button onClick={()=>void load()} className="rounded-xl border p-2"><RefreshCcw className="h-4 w-4"/></button></div>{loading?<div className="p-12 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-slate-400"/></div>:<div className="divide-y">{rows.map(r=>{const cashWait=['aguardando_dinheiro','aguardando_troco'].includes(r.status);return <div key={r.id} className="grid gap-3 p-4 lg:grid-cols-[1fr_auto_auto_auto] lg:items-center"><div><div className="font-black">Venda {r.codigo}</div><div className="mt-1 text-xs text-slate-400">{new Date(r.created_at).toLocaleString('pt-BR')} • {r.cliente_nome||'Cliente não identificado'}</div>{r.cash_change_cents>0&&<div className="mt-1 text-xs font-black text-amber-700">Troco: {formatarBRL(r.cash_change_cents/100)}</div>}</div><div className="font-black">{formatarBRL(Number(r.total))}</div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-black ${r.status==='pago'?'bg-lime-100 text-lime-800':cashWait?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-600'}`}>{String(r.status).replaceAll('_',' ').toUpperCase()}</span><div className="flex gap-2">{cashWait&&<button disabled={busy===r.codigo} onClick={()=>void confirm(r.codigo)} className="inline-flex items-center gap-1 rounded-xl bg-[#6D28D9] px-3 py-2 text-xs font-black text-white"><Check className="h-3.5 w-3.5"/>{busy===r.codigo?'Confirmando…':Number(r.cash_change_cents||0)>0?'Troco entregue e dinheiro recebido':'Dinheiro recebido'}</button>}{r.status==='pago'&&r.receipt_token&&<Link target="_blank" href={`https://${slug}.funcionaria.net/recibo/${r.receipt_token}`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-600">Comprovante</Link>}</div></div>})}{!rows.length&&<div className="p-10 text-center text-sm font-bold text-slate-400">Nenhum recebimento ainda.</div>}</div>}</div></div>
}
