import PixWikiPublicPage from '@/components/pix/PixWikiPublicPage';

export default function PixWikiTermsPage() {
  return <PixWikiPublicPage eyebrow="Termos" title="Termos de Uso — PixWiki" intro="Última atualização: 1º de outubro de 2026. A PixWiki é uma camada tecnológica de confirmação, conciliação e automação de Pix; não é banco, instituição de pagamento, carteira ou serviço de custódia.">
    <section><h2>1. Serviço</h2><p>A PixWiki conecta-se, mediante autorização do usuário, a uma conta Mercado Pago compatível para identificar recebimentos e oferecer dashboard, Pix Link, Checkout, API, notificações, Webhooks, relatórios e recursos de equipe. O dinheiro permanece no provedor financeiro escolhido pelo usuário.</p></section>
    <section><h2>2. Conta Mercado Pago</h2><p>O usuário é responsável pela titularidade, regularidade, permissões e regras da própria conta Mercado Pago. Tarifas ou limitações cobradas pelo Mercado Pago ou por outras instituições financeiras são independentes da PixWiki.</p></section>
    <section><h2>3. Automação PixWiki</h2><p><strong>Um pagamento automatizado consome no máximo uma Automação PixWiki</strong>, mesmo quando mais de um canal pago participa do mesmo recebimento. Receber Pix diretamente na própria chave, visualizar dashboard/histórico e Push não consomem automação paga. Cobranças não pagas, canceladas ou falhas também não consomem.</p></section>
    <section><h2>4. Planos e excedente</h2><p>Os planos vigentes exibidos na contratação definem franquia, mensalidade/anuidade e preço do excedente. O usuário pode limitar gastos e desativar excedente. Quando a franquia se esgota sem excedente autorizado, novas automações pagas podem ser pausadas, mas o recebimento do Pix, o histórico e o Push continuam disponíveis.</p><p>A proteção de faixa econômica compara, no fechamento mensal, o custo aplicável às faixas mensais disponíveis e utiliza o menor valor compatível com aquele volume, conforme as regras mostradas na contratação.</p></section>
    <section><h2>5. Desconto de conveniência</h2><p>Quando necessário para distinguir pagamentos simultâneos do mesmo valor, a PixWiki pode gerar um Pix com desconto de conveniência de até R$ 0,10. O desconto concedido ao pagador vira crédito de cobrança PixWiki para o recebedor. Esse crédito não é saldo financeiro, não pode ser sacado e só pode compensar cobranças PixWiki.</p></section>
    <section><h2>6. Confirmação e disponibilidade</h2><p>A confirmação depende de APIs, disponibilidade de rede e informações fornecidas pelo provedor financeiro. A PixWiki trabalha para identificar pagamentos rapidamente, mas não promete confirmação instantânea nem substitui o extrato oficial da instituição financeira.</p></section>
    <section><h2>7. API e Webhooks</h2><p>O usuário deve manter chaves API e segredos de Webhook em ambiente seguro, implementar idempotência e validar assinaturas. Integrações não devem assumir que uma tentativa de entrega significa processamento único; o identificador do evento deve ser usado para deduplicação.</p></section>
    <section><h2>8. Uso aceitável</h2><p>É proibido usar a PixWiki para fraude, lavagem de dinheiro, engenharia social, violação de direitos, tentativa de acesso não autorizado, abuso da infraestrutura ou atividade ilegal. Podemos restringir recursos quando necessário para segurança, cumprimento legal ou proteção da plataforma.</p></section>
    <section><h2>9. Cancelamento e cobrança</h2><p>Cancelamento, renovação e eventual reembolso seguem as condições exibidas no momento da contratação e a legislação aplicável. Obrigações já vencidas e registros necessários a auditoria/obrigações legais podem permanecer após o cancelamento.</p></section>
    <section><h2>10. Contato</h2><p>Dúvidas sobre estes termos podem ser enviadas para <a href="mailto:contato@bigcorps.com.br">contato@bigcorps.com.br</a>.</p></section>
  </PixWikiPublicPage>;
}
