import { createClient } from 'jsr:@supabase/supabase-js@2'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,jsonHeaders={'Content-Type':'application/json'}
const retryMinutes:Record<number,number>={1:1,2:5,3:30,4:120}
async function secret(s:any){const{data}=await s.from('pixwiki_internal_secrets').select('secret').eq('key','webhook_internal').maybeSingle();return data?.secret?String(data.secret):''}
async function auth(s:any,r:Request){const e=await secret(s);return!!e&&r.headers.get('x-pixwiki-internal-key')===e}
async function hmac(sec:string,v:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(sec),{name:'HMAC',hash:'SHA-256'},false,['sign']);const b=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function privateIp(h:string){const m=h.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);if(!m)return false;const a=+m[1],b=+m[2];return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}
function safeUrl(raw:string){let u:URL;try{u=new URL(raw)}catch{throw new Error('invalid_webhook_url')}if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443'))throw new Error('invalid_webhook_url');const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(!h||h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h==='::1'||h.startsWith('fc')||h.startsWith('fd')||h.startsWith('fe80:')||privateIp(h))throw new Error('private_webhook_host_not_allowed');return u.toString()}
async function ensureEvent(s:any,id:string){const{data:old}=await s.from('pixwiki_webhook_events').select('*').eq('receipt_id',id).eq('event_type','pix.received').maybeSingle();if(old)return old;const{data:r}=await s.from('mp_received_payments').select('id,user_id,company_id,mp_payment_id,amount_cents,fee_amount_cents,net_amount_cents,status,source,date_approved,date_created').eq('id',id).eq('status','approved').maybeSingle();if(!r)throw new Error('receipt_not_found');const[{data:f},{data:c}]=await Promise.all([s.rpc('pixwiki_has_feature_for_user',{p_user_id:r.user_id,p_feature:'webhooks'}),s.from('companies').select('id,name,slug').eq('id',r.company_id).maybeSingle()]);if(f!==true)return null;if(!c)throw new Error('company_not_found');const eid=crypto.randomUUID(),created=new Date().toISOString(),payload={event:'pix.received',id:eid,created_at:created,data:{receipt_id:r.id,company:{id:c.id,name:c.name,slug:c.slug},mp_payment_id:r.mp_payment_id,source:r.source,amount_cents:r.amount_cents,fee_amount_cents:r.fee_amount_cents,net_amount_cents:r.net_amount_cents,currency:'BRL',status:r.status,received_at:r.date_approved||r.date_created||created}};const{data,error}=await s.from('pixwiki_webhook_events').insert({id:eid,user_id:r.user_id,company_id:r.company_id,receipt_id:r.id,event_type:'pix.received',payload}).select('*').single();if(!error)return data;const{data:race}=await s.from('pixwiki_webhook_events').select('*').eq('receipt_id',id).eq('event_type','pix.received').maybeSingle();if(race)return race;throw error}
async function ensureDeliveries(s:any,e:any){const{data:h,error}=await s.from('pixwiki_webhooks').select('id').eq('user_id',e.user_id).eq('is_active',true).contains('event_types',['pix.received']).or(`company_id.is.null,company_id.eq.${e.company_id}`);if(error)throw error;for(const x of h||[])await s.from('pixwiki_webhook_deliveries').upsert({event_id:e.id,webhook_id:x.id,status:'pending'},{onConflict:'event_id,webhook_id',ignoreDuplicates:true})}
async function deliver(s:any,d:any){const[{data:e},{data:h}]=await Promise.all([s.from('pixwiki_webhook_events').select('*').eq('id',d.event_id).maybeSingle(),s.from('pixwiki_webhooks').select('*').eq('id',d.webhook_id).maybeSingle()]);if(!e||!h||h.is_active!==true){await s.from('pixwiki_webhook_deliveries').update({status:'failed',last_error:'webhook_or_event_unavailable',updated_at:new Date().toISOString()}).eq('id',d.id);return{id:d.id,ok:false}}const{data:sr}=await s.from('pixwiki_webhook_secrets').select('signing_secret').eq('webhook_id',h.id).maybeSingle();if(!sr?.signing_secret)throw new Error('webhook_secret_missing');const attempt=Number(d.attempt_count||0)+1,now=new Date(),ts=Math.floor(now.getTime()/1000).toString(),raw=JSON.stringify(e.payload),sig=await hmac(String(sr.signing_secret),`${ts}.${raw}`);let code:null|number=null,body='',err='',ok=false;try{const r=await fetch(safeUrl(String(h.url)),{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'PixWiki-Webhooks/1.0','X-PixWiki-Event':e.event_type,'X-PixWiki-Event-Id':e.id,'X-PixWiki-Timestamp':ts,'X-PixWiki-Signature':`v1=${sig}`,'Idempotency-Key':e.id},body:raw,signal:AbortSignal.timeout(8000)});code=r.status;body=(await r.text()).slice(0,1000);ok=r.ok;if(!ok)err=`HTTP ${r.status}`}catch(x){err=x instanceof Error?x.message:'delivery_failed'}const u:any={attempt_count:attempt,response_status:code,response_body:body||null,last_error:err||null,last_attempt_at:now.toISOString(),updated_at:now.toISOString()};if(ok){u.status='delivered';u.delivered_at=now.toISOString();u.next_attempt_at=null;await Promise.all([s.from('pixwiki_webhook_deliveries').update(u).eq('id',d.id),s.from('pixwiki_webhooks').update({last_success_at:now.toISOString(),last_status_code:code,updated_at:now.toISOString()}).eq('id',h.id)]);return{id:d.id,ok:true,status:code,attempt}}if(attempt>=5){u.status='failed';u.next_attempt_at=null}else{u.status='retrying';u.next_attempt_at=new Date(now.getTime()+(retryMinutes[attempt]??120)*60000).toISOString()}await Promise.all([s.from('pixwiki_webhook_deliveries').update(u).eq('id',d.id),s.from('pixwiki_webhooks').update({last_failure_at:now.toISOString(),last_status_code:code,updated_at:now.toISOString()}).eq('id',h.id)]);return{id:d.id,ok:false,status:code,attempt,retry:u.status==='retrying',error:err}}
async function event(s:any,id:string){const e=await ensureEvent(s,id);if(!e)return{skipped:true,reason:'pix_pro_required'};await ensureDeliveries(s,e);const{data:d}=await s.from('pixwiki_webhook_deliveries').select('*').eq('event_id',e.id).eq('status','pending');const out=[];for(const x of d||[])out.push(await deliver(s,x));return{event_id:e.id,deliveries:out}}
async function due(s:any){const now=new Date().toISOString();const{data:d,error}=await s.from('pixwiki_webhook_deliveries').select('*').in('status',['pending','retrying']).or(`next_attempt_at.is.null,next_attempt_at.lte.${now}`).order('created_at',{ascending:true}).limit(50);if(error)throw error;const out=[];for(const x of d||[])out.push(await deliver(s,x));return out}
Deno.serve(async r=>{if(r.method!=='POST')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers:jsonHeaders});const s=createClient(SUPABASE_URL,SERVICE_ROLE);try{if(!(await auth(s,r)))return new Response(JSON.stringify({error:'not_found'}),{status:404,headers:jsonHeaders});const b=await r.json().catch(()=>({}));if(b?.retry_due===true){const x=await due(s);return new Response(JSON.stringify({ok:true,processed:x.length,results:x}),{headers:jsonHeaders})}const id=String(b?.receipt_id||'');if(!id)return new Response(JSON.stringify({error:'receipt_id_required'}),{status:400,headers:jsonHeaders});return new Response(JSON.stringify({ok:true,...await event(s,id)}),{headers:jsonHeaders})}catch(e){const m=e instanceof Error?e.message:'internal_error';console.error('[pixwiki-webhook-dispatch]',m);return new Response(JSON.stringify({ok:false,error:m}),{status:500,headers:jsonHeaders})}})
