import PixWikiPublicPage from '@/components/pix/PixWikiPublicPage';

export default function PixWikiPrivacyPage() {
  return <PixWikiPublicPage eyebrow="Privacidade" title="Aviso de Privacidade — PixWiki" intro="Última atualização: 1º de outubro de 2026. Este aviso explica, em linguagem direta, como a PixWiki trata dados necessários para operar confirmação, automação e conciliação de Pix.">
    <section><h2>1. Quem é responsável</h2><p>A PixWiki é um produto da <strong>BigCorps Tecnologia Ltda.</strong> Para assuntos de privacidade e proteção de dados, o canal é <a href="mailto:contato@bigcorps.com.br">contato@bigcorps.com.br</a>.</p></section>
    <section><h2>2. Dados tratados</h2><ul><li>dados de conta, empresa, contatos e membros da equipe;</li><li>chave Pix cadastrada e configurações do recebedor;</li><li>tokens OAuth e identificadores técnicos da conexão com o Mercado Pago, mantidos no servidor;</li><li>dados de recebimentos necessários para identificação e conciliação, como valores, horários, identificadores do provedor e metadados associados;</li><li>dados de Checkout/API informados pelo cliente, incluindo referência externa, nome/e-mail/telefone do pagador quando enviados e metadata;</li><li>destinos de notificação, chaves API, configurações de Webhook e logs técnicos/de segurança;</li><li>cookies, telemetria e dados de uso necessários para segurança, suporte e melhoria do serviço.</li></ul></section>
    <section><h2>3. Finalidades e bases</h2><p>Tratamos dados para executar o serviço contratado, autenticar usuários, detectar e conciliar pagamentos, entregar notificações e Webhooks, faturar o uso, prevenir fraude/abuso, atender suporte e cumprir obrigações legais. As bases legais aplicáveis podem incluir execução de contrato, cumprimento de obrigação legal/regulatória, legítimo interesse e consentimento, conforme o caso.</p></section>
    <section><h2>4. Compartilhamentos</h2><p>Podemos usar fornecedores de infraestrutura, banco de dados, hospedagem, autenticação, Push, e-mail e WhatsApp, além do Mercado Pago para a conexão autorizada pelo usuário. Cada fornecedor recebe somente o necessário para sua função. Dados também podem ser apresentados a autoridades quando houver obrigação legal válida.</p></section>
    <section><h2>5. Dinheiro e credenciais</h2><p>A PixWiki <strong>não recebe, guarda ou custodia o dinheiro do usuário</strong>. Os valores permanecem na conta Mercado Pago conectada. Credenciais privilegiadas e tokens de integração são tratados no backend e não devem ser expostos ao navegador.</p></section>
    <section><h2>6. Retenção e exclusão</h2><p>Dados são mantidos pelo tempo necessário à prestação do serviço, segurança, auditoria, cobrança e cumprimento de obrigações legais. Uma solicitação de exclusão pode ser feita na página <a href="/exclusao">Exclusão de dados</a>. Alguns registros podem precisar ser retidos pelo prazo legal aplicável.</p></section>
    <section><h2>7. Seus direitos</h2><p>Nos termos da LGPD, quando aplicável, você pode solicitar confirmação de tratamento, acesso, correção, portabilidade, informação sobre compartilhamentos, oposição e exclusão, observadas as hipóteses legais de retenção.</p></section>
    <section><h2>8. Segurança</h2><p>Adotamos controles de acesso, segregação de papéis, tokens opacos, idempotência e assinatura de Webhooks. Veja a página de <a href="/seguranca">Segurança</a> para a visão operacional.</p></section>
  </PixWikiPublicPage>;
}
