import { createClient } from 'jsr:@supabase/supabase-js@2'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!, SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const cors={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'GET, OPTIONS'}
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function intParam(v:string|null,f:number,min:number,max:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.floor(n))):f}
function isoDate(raw:string|null,fallback:Date){if(!raw)return fallback.toISOString();const d=new Date(raw);if(!Number.isFinite(d.getTime()))throw new Error('invalid_date');return d.toISOString()}
async function authKey(s:any,req:Request){const raw=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!raw.startsWith('pw_live_')||raw.length<24)return null;const h=await sha256(raw);const {data:k}=await s.from('pixwiki_api_keys').select('id,user_id,name,key_prefix,revoked_at').eq('key_hash',h).is('revoked_at',null).maybeSingle();if(!k)return null;const {data:e}=await s.rpc('pixwiki_has_feature_for_user',{p_user_id:k.user_id,p_feature:'api'});return e===true?k:{...k,disabled:true}}
async function log(s:any,k:any,m:string,p:string,status:number,start:number){if(!k?.id)return;await Promise.all([s.from('pixwiki_api_request_logs').insert({user_id:k.user_id,api_key_id:k.id,method:m,path:p.slice(0,500),status_code:status,duration_ms:Math.max(0,Date.now()-start)}),s.from('pixwiki_api_keys').update({last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',k.id)])}
function receipt(r:any){return{id:r.id,company_id:r.company_id,mp_payment_id:r.mp_payment_id??null,amount_cents:Number(r.amount_cents||0),fee_amount_cents:Number(r.fee_amount_cents||0),net_amount_cents:Number(r.net_amount_cents||0),currency:'BRL',status:r.status,source:r.source,provider:r.provider,received_at:r.received_at}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const started=Date.now(),s=createClient(SUPABASE_URL,SERVICE_ROLE),url=new URL(req.url);let path=url.searchParams.get('resource')||'/';if(!path.startsWith('/'))path=`/${path}`;let key:any=null;const finish=async(status:number,body:any)=>{await log(s,key,req.method,path,status,started);return new Response(JSON.stringify(body),{status,headers:cors})};try{
 if(req.method!=='GET')return await finish(405,{error:'method_not_allowed'});key=await authKey(s,req);if(!key)return await finish(401,{error:'invalid_api_key'});if(key.disabled)return await finish(403,{error:'pix_pro_required'});
 const minute=new Date(Date.now()-60000).toISOString();const {count}=await s.from('pixwiki_api_request_logs').select('id',{count:'exact',head:true}).eq('api_key_id',key.id).gte('created_at',minute);if(Number(count||0)>=120)return await finish(429,{error:'rate_limit_exceeded',retry_after_seconds:60});
 if(path==='/companies'){
  const {data:companies,error}=await s.from('companies').select('id,name,slug,logo_url,is_active').eq('user_id',key.user_id).eq('segment_key','pix_wiki').order('created_at',{ascending:true});if(error)throw error;const ids=(companies||[]).map((c:any)=>c.id);let connected=new Set<string>();if(ids.length){const {data:conns}=await s.from('pixwiki_mp_connections').select('company_id').in('company_id',ids).eq('is_active',true);connected=new Set((conns||[]).map((c:any)=>String(c.company_id)))}return await finish(200,{data:(companies||[]).map((c:any)=>({id:c.id,name:c.name,slug:c.slug,is_active:c.is_active,mp_connected:connected.has(String(c.id))}))})
 }
 if(path==='/summary'){
  const companyId=url.searchParams.get('company_id'),source=url.searchParams.get('source')||'all';if(!['all','pix_key','pixwiki_link'].includes(source))return await finish(400,{error:'invalid_source'});if(companyId){const {data:c}=await s.from('companies').select('id').eq('id',companyId).eq('user_id',key.user_id).eq('segment_key','pix_wiki').maybeSingle();if(!c)return await finish(403,{error:'company_not_allowed'})}const end=new Date(),start=new Date(end.getTime()-30*86400000),from=isoDate(url.searchParams.get('from'),start),to=isoDate(url.searchParams.get('to'),end);const {data,error}=await s.rpc('pixwiki_api_summary_internal',{p_user_id:key.user_id,p_company_id:companyId||null,p_source:source,p_start_at:from,p_end_at:to});if(error)throw error;return await finish(200,{data:data?.[0]||{receipt_count:0,gross_cents:0,fee_cents:0,net_cents:0,pix_key_count:0,pix_link_count:0},from,to})
 }
 if(path==='/receipts'){
  const companyId=url.searchParams.get('company_id'),source=url.searchParams.get('source')||'all',status=url.searchParams.get('status')||'all',limit=intParam(url.searchParams.get('limit'),50,1,100),offset=intParam(url.searchParams.get('offset'),0,0,10000);if(!['all','pix_key','pixwiki_link'].includes(source))return await finish(400,{error:'invalid_source'});if(!['all','approved','confirmed'].includes(status))return await finish(400,{error:'invalid_status'});const end=new Date(),start=new Date(end.getTime()-30*86400000),from=isoDate(url.searchParams.get('from'),start),to=isoDate(url.searchParams.get('to'),end);let q=s.from('pixwiki_receipts').select('id,company_id,user_id,mp_payment_id,amount_cents,fee_amount_cents,net_amount_cents,status,source,provider,received_at',{count:'exact'}).eq('user_id',key.user_id).gte('received_at',from).lt('received_at',to).order('received_at',{ascending:false}).range(offset,offset+limit-1);if(companyId)q=q.eq('company_id',companyId);if(source!=='all')q=q.eq('source',source);if(status!=='all')q=q.eq('status',status);const {data,error,count:total}=await q;if(error)throw error;return await finish(200,{data:(data||[]).map(receipt),pagination:{limit,offset,total:total||0}})
 }
 const match=path.match(/^\/receipts\/([0-9a-f-]{36})$/i);if(match){const {data,error}=await s.from('pixwiki_receipts').select('id,company_id,user_id,mp_payment_id,amount_cents,fee_amount_cents,net_amount_cents,status,source,provider,received_at').eq('id',match[1]).eq('user_id',key.user_id).maybeSingle();if(error)throw error;if(!data)return await finish(404,{error:'receipt_not_found'});return await finish(200,{data:receipt(data)})}
 return await finish(404,{error:'not_found',endpoints:['/companies','/receipts','/receipts/:id','/summary']})
 }catch(error){const msg=error instanceof Error?error.message:'internal_error';console.error('[pixwiki-api]',msg);return await finish(msg==='invalid_date'?400:500,{error:msg})}})
