'use client';

import { useCallback, useEffect, useState } from 'react';
import { BadgeDollarSign, RefreshCw, TrendingUp, TriangleAlert } from 'lucide-react';
import type { AdminIdentity, AdminMarginSnapshot, FinanceProductKey } from '@/types/platform-admin-business';
import AdminHeader from './AdminHeader';
import { BusinessError, BusinessLoading, BusinessMetric, money, pct, usd } from './AdminBusinessUi';
import { MarginProductsChart } from './AdminBusinessCharts';

type Props={admin:AdminIdentity;basePath:''|'/admin'};
const LABELS:Record<FinanceProductKey,string>={minhai:'minhAi',minia:'min.IA',artefinal:'ArteFinal',pixwiki:'PixWiki',consultatec:'ConsultaTec',conviteia:'ConviteIA',melhoria:'MelhorIA',funcionaria:'FuncionarIA',shared_credits:'Créditos compartilhados'};
export default function AdminMargin({admin,basePath}:Props){
 const [data,setData]=useState<AdminMarginSnapshot|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const loginPath=`${basePath}/login`;
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch('/api/admin/margem',{cache:'no-store',credentials:'same-origin'});if(r.status===401||r.status===403){window.location.assign(loginPath);return}if(!r.ok)throw new Error(r.status===503?'A estrutura de margem ainda não está disponível no banco.':'Não foi possível carregar margem.');const p=await r.json();if(!p?.ok||!p.data)throw new Error('Resposta de margem inválida.');setData(p.data)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.')}finally{setLoading(false)}},[loginPath]);useEffect(()=>{void load()},[load]);
 return <main className="min-h-screen bg-slate-950 text-white"><AdminHeader admin={admin} basePath={basePath} active="margin"/><div className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-lime-300">Unit economics</p><h1 className="mt-2 text-3xl font-black">Margem</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Contribuição calculada somente sobre custos que o sistema realmente conhece. Não é lucro contábil.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-sm font-bold text-slate-300"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Atualizar</button></div>{error?<BusinessError message={error} onRetry={()=>void load()}/>:null}{loading&&!data?<BusinessLoading text="Cruzando receita e custos conhecidos..."/>:data?<>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><BusinessMetric title="Receita no mês" value={money(data.summary.revenueMonthCents)} icon={<BadgeDollarSign className="h-5 w-5"/>}/><BusinessMetric title="Custos conhecidos" value={money(data.summary.knownCostMonthCents)} subtitle="BRL atribuível + fixos"/><BusinessMetric title="Contribuição" value={money(data.summary.contributionMonthCents)} emphasized icon={<TrendingUp className="h-5 w-5"/>}/><BusinessMetric title="Margem conhecida" value={pct(data.summary.marginPct)} subtitle="não inclui custos não rastreados"/></section>
 <div className="mt-5 flex gap-3 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4"><TriangleAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-300"/><div><p className="text-sm font-bold text-amber-100">Margem conservadora</p><p className="mt-1 text-xs leading-5 text-slate-500">{data.note}</p>{data.sharedKnownCostCents>0?<p className="mt-2 text-xs text-slate-400">Custos compartilhados sem atribuição por produto: <strong className="text-white">{money(data.sharedKnownCostCents)}</strong>.</p>:null}{data.openai?.available&&data.openai.costMonthUsdCents?<p className="mt-2 text-xs text-slate-400">OpenAI no mês: <strong className="text-white">{usd(data.openai.costMonthUsdCents)}</strong>, exibido separadamente porque não há conversão cambial/atribuição por produto confiável nesta base.</p>:null}</div></div>
 <section className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><article className="rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><h2 className="font-black">Contribuição por produto</h2><p className="mt-1 text-xs text-slate-600">Receita menos custos BRL conhecidos</p><div className="mt-5"><MarginProductsChart products={data.products}/></div></article><article className="rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><h2 className="font-black">Produtos</h2><div className="mt-4 overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead className="text-[11px] uppercase tracking-[.12em] text-slate-600"><tr><th className="pb-3">Produto</th><th className="pb-3 text-right">Receita</th><th className="pb-3 text-right">Custo conhecido</th><th className="pb-3 text-right">Contribuição</th><th className="pb-3 text-right">Margem</th></tr></thead><tbody className="divide-y divide-white/[.06]">{data.products.map(p=><tr key={p.productKey}><td className="py-3"><p className="font-bold">{LABELS[p.productKey]}</p>{p.costEvents===0?<p className="text-[11px] text-amber-300/70">sem custo variável atribuído</p>:null}</td><td className="py-3 text-right">{money(p.revenueCents)}</td><td className="py-3 text-right text-slate-400">{money(p.knownCostCents)}</td><td className="py-3 text-right font-bold">{money(p.contributionCents)}</td><td className="py-3 text-right">{pct(p.marginPct)}</td></tr>)}</tbody></table></div></article></section>
 <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:p-6"><h2 className="font-black">Clientes por contribuição conhecida</h2><p className="mt-1 text-xs text-slate-600">Somente clientes com receita no mês ou custo atribuído.</p><div className="mt-4 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="text-[11px] uppercase tracking-[.12em] text-slate-600"><tr><th className="pb-3">Cliente</th><th className="pb-3 text-right">Receita</th><th className="pb-3 text-right">Custo</th><th className="pb-3 text-right">Contribuição</th><th className="pb-3 text-right">Margem</th></tr></thead><tbody className="divide-y divide-white/[.06]">{data.customers.slice(0,50).map(c=><tr key={c.userId}><td className="py-3"><p className="font-semibold">{c.name||c.email||'Usuário'}</p><p className="text-xs text-slate-600">{c.email}</p></td><td className="py-3 text-right">{money(c.revenueCents)}</td><td className="py-3 text-right text-slate-400">{money(c.knownCostCents)}</td><td className="py-3 text-right font-bold">{money(c.contributionCents)}</td><td className="py-3 text-right">{pct(c.marginPct)}</td></tr>)}</tbody></table></div></section>
 </>:null}</div></main>
}
