'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase-browser';
import PixWikiHeader, { type PixWikiPlanKey } from '@/components/pix/PixWikiHeader';
import PixWikiDashboardNav from '@/components/pix/PixWikiDashboardNav';

const FUNCTIONS_URL=`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1`;
const ANON_KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
type KeyRow={id:string;name:string;key_prefix:string;last_used_at:string|null;revoked_at:string|null;created_at:string};
type Hook={id:string;company_id:string|null;name:string;url:string;is_active:boolean;last_success_at:string|null;last_failure_at:string|null;last_status_code:number|null};
type Company={id:string;name:string;slug:string};
type Snap={billing:{plan:PixWikiPlanKey};companies:Company[]};
function dt(v:string|null){return v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}

export default function PixWikiApiPage(){
 const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const[dark,setDark]=useState(true);const[loading,setLoading]=useState(true);const[snap,setSnap]=useState<Snap|null>(null);const[keys,setKeys]=useState<KeyRow[]>([]);const[hooks,setHooks]=useState<Hook[]>([]);const[keyName,setKeyName]=useState('Integração principal');const[newKey,setNewKey]=useState('');const[hookName,setHookName]=useState('Meu sistema');const[hookUrl,setHookUrl]=useState('');const[hookCompany,setHookCompany]=useState('');const[newSecret,setNewSecret]=useState('');const[busy,setBusy]=useState('');const[notice,setNotice]=useState('');const[error,setError]=useState('');
 const callEdge=useCallback(async(body:Record<string,unknown>)=>{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Sessão expirada');const r=await fetch(`${FUNCTIONS_URL}/pixwiki-api-admin`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:ANON_KEY},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error||`HTTP ${r.status}`);return d},[supabase]);
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/pix/login');return}const active=localStorage.getItem('pixWikiActiveCompanyId');const[{data:s,error:se},k,h]=await Promise.all([supabase.rpc('pixwiki_v2_dashboard_snapshot',{p_company_id:active||null}),callEdge({action:'list_keys'}),callEdge({action:'list_webhooks'})]);if(se)throw se;setSnap(s as Snap);setKeys(k.keys||[]);setHooks(h.webhooks||[]);setLoading(false)},[callEdge,router,supabase]);
 useEffect(()=>{const saved=localStorage.getItem('publicTheme');setDark(saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches);load().catch(()=>{setError('Não foi possível carregar as integrações.');setLoading(false)})},[load]);
 async function createKey(){setBusy('key');setError('');setNewKey('');try{const r=await callEdge({action:'create_key',name:keyName.trim()||'Chave API'});setNewKey(r.secret||'');setNotice('Chave criada. Copie agora: ela não será exibida novamente.');await load()}catch(e:any){setError(String(e?.message||'').includes('limit')?'Limite de chaves atingido.':'Não foi possível criar a chave.')}finally{setBusy('')}}
 async function revokeKey(id:string){if(!confirm('Revogar esta chave?'))return;setBusy(id);try{await callEdge({action:'revoke_key',key_id:id});await load();setNotice('Chave revogada.')}catch{setError('Não foi possível revogar a chave.')}finally{setBusy('')}}
 async function createHook(){if(!hookUrl.trim()){setError('Informe uma URL HTTPS.');return}setBusy('hook');setNewSecret('');setError('');try{const r=await callEdge({action:'create_webhook',name:hookName.trim()||'Webhook',url:hookUrl.trim(),company_id:hookCompany||null});setNewSecret(r.signing_secret||'');setHookUrl('');setNotice('Webhook criado. Copie o segredo de assinatura agora.');await load()}catch(e:any){setError(String(e?.message||'').includes('private')?'URLs privadas/locais não são permitidas.':'Não foi possível criar o webhook.')}finally{setBusy('')}}
 async function updateHook(h:Hook,patch:Record<string,unknown>,msg='Webhook atualizado.'){setBusy(h.id);try{await callEdge({action:'update_webhook',webhook_id:h.id,...patch});await load();setNotice(msg)}catch{setError('Não foi possível alterar o webhook.')}finally{setBusy('')}}
 async function testHook(h:Hook){setBusy(`test-${h.id}`);try{const r=await callEdge({action:'test_webhook',webhook_id:h.id});setNotice(`Teste entregue com HTTP ${r?.result?.status??200}.`);await load()}catch{setError('O endpoint não respondeu com HTTP 2xx.')}finally{setBusy('')}}
 async function rotate(h:Hook){if(!confirm('Gerar um novo segredo? O anterior deixa de validar.'))return;setBusy(`rotate-${h.id}`);setNewSecret('');try{const r=await callEdge({action:'rotate_webhook_secret',webhook_id:h.id});setNewSecret(r.signing_secret||'');setNotice('Novo segredo gerado.')}catch{setError('Não foi possível rotacionar o segredo.')}finally{setBusy('')}}
 async function del(h:Hook){if(!confirm(`Excluir o webhook "${h.name}"?`))return;setBusy(`del-${h.id}`);try{await callEdge({action:'delete_webhook',webhook_id:h.id});await load();setNotice('Webhook excluído.')}catch{setError('Não foi possível excluir o webhook.')}finally{setBusy('')}}
 async function copy(v:string){await navigator.clipboard.writeText(v);setNotice('Copiado.');}
 if(loading||!snap)return <main className="min-h-screen bg-[#020617] text-white flex items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-white/15 border-t-emerald-400"/></main>;
 const page=dark?'bg-[#020617] text-white':'bg-[#f7f8fa] text-slate-900';const card=dark?'border-white/10 bg-white/[0.035]':'border-black/10 bg-white shadow-sm';const inner=dark?'border-white/10 bg-black/15':'border-black/10 bg-slate-50';const muted=dark?'text-white/55':'text-slate-500';const input=dark?'border-white/10 bg-white/[0.05] text-white':'border-black/10 bg-white text-slate-900';
 return <main className={`min-h-screen pb-28 ${page}`}><div className="mx-auto w-full max-w-6xl px-4 py-6 sm:px-6"><PixWikiHeader plan={snap.billing.plan} dark={dark} onThemeChange={setDark}/><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black">API & Webhooks</h1><p className={`mt-2 text-sm ${muted}`}>Disponíveis em todas as faixas. O uso é medido quando um pagamento é efetivamente automatizado.</p></div><Link href="https://pix.wiki/api/pixwiki/v1" target="_blank" className={`rounded-xl border px-4 py-2.5 text-xs font-black ${card}`}>Endpoint da API</Link></div>{(notice||error)&&<div className={`mt-4 rounded-2xl border p-4 text-sm ${error?'border-red-500/25 bg-red-500/10 text-red-300':'border-emerald-500/25 bg-emerald-500/10 text-emerald-300'}`}>{error||notice}</div>}
 <section className={`mt-6 rounded-3xl border p-6 ${card}`}><h2 className="text-lg font-black">Chaves de API</h2><p className={`mt-1 text-sm ${muted}`}>Use no servidor. Nunca exponha `pw_live_...` no navegador.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={keyName} onChange={e=>setKeyName(e.target.value)} className={`flex-1 rounded-xl border px-3 py-3 text-sm outline-none ${input}`}/><button onClick={createKey} disabled={busy==='key'} className="rounded-xl bg-emerald-500 px-5 py-3 text-sm font-black text-slate-950 disabled:opacity-50">{busy==='key'?'Criando…':'Criar chave'}</button></div>{newKey&&<div className="mt-4 rounded-2xl border border-amber-500/25 bg-amber-500/10 p-4"><p className="text-xs font-black text-amber-300">MOSTRADA UMA ÚNICA VEZ</p><p className="mt-2 break-all font-mono text-sm">{newKey}</p><button onClick={()=>copy(newKey)} className="mt-3 rounded-xl bg-amber-400 px-4 py-2 text-xs font-black text-slate-950">Copiar</button></div>}<div className="mt-4 space-y-2">{keys.length===0?<div className={`rounded-2xl border p-5 text-sm ${inner} ${muted}`}>Nenhuma chave criada.</div>:keys.map(k=><div key={k.id} className={`flex items-center justify-between gap-3 rounded-2xl border p-4 ${inner}`}><div><p className="text-sm font-black">{k.name}</p><p className={`mt-1 font-mono text-xs ${muted}`}>{k.key_prefix}•••• · último uso {dt(k.last_used_at)}</p></div><button onClick={()=>revokeKey(k.id)} disabled={!!k.revoked_at||busy===k.id} className={`rounded-xl border px-3 py-2 text-xs font-black ${card} disabled:opacity-40`}>{k.revoked_at?'Revogada':'Revogar'}</button></div>)}</div></section>
 <section className={`mt-4 rounded-3xl border p-6 ${card}`}><h2 className="text-lg font-black">Webhooks</h2><p className={`mt-1 text-sm ${muted}`}>Receba `pix.received` com assinatura HMAC, contexto de Checkout/API e retries automáticos.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={hookName} onChange={e=>setHookName(e.target.value)} placeholder="Nome" className={`rounded-xl border px-3 py-3 text-sm outline-none ${input}`}/><input value={hookUrl} onChange={e=>setHookUrl(e.target.value)} placeholder="https://seusistema.com/webhooks/pixwiki" className={`rounded-xl border px-3 py-3 text-sm outline-none ${input}`}/><select value={hookCompany} onChange={e=>setHookCompany(e.target.value)} className={`rounded-xl border px-3 py-3 text-sm outline-none ${input}`} style={{colorScheme:dark?'dark':'light'}}><option value="">Todas as empresas</option>{snap.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={createHook} disabled={busy==='hook'} className="rounded-xl bg-sky-500 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy==='hook'?'Criando…':'Criar webhook'}</button></div>{newSecret&&<div className="mt-4 rounded-2xl border border-amber-500/25 bg-amber-500/10 p-4"><p className="text-xs font-black text-amber-300">SEGREDO DE ASSINATURA</p><p className="mt-2 break-all font-mono text-sm">{newSecret}</p><button onClick={()=>copy(newSecret)} className="mt-3 rounded-xl bg-amber-400 px-4 py-2 text-xs font-black text-slate-950">Copiar</button></div>}<div className="mt-4 space-y-2">{hooks.length===0?<div className={`rounded-2xl border p-5 text-sm ${inner} ${muted}`}>Nenhum webhook configurado.</div>:hooks.map(h=><div key={h.id} className={`rounded-2xl border p-4 ${inner}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><p className="font-black">{h.name}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-black ${h.is_active?'bg-emerald-500/10 text-emerald-400':'bg-slate-500/10 text-slate-400'}`}>{h.is_active?'ATIVO':'PAUSADO'}</span></div><p className={`mt-1 break-all text-xs ${muted}`}>{h.url}</p><p className={`mt-1 text-[11px] ${muted}`}>Último sucesso {dt(h.last_success_at)} · HTTP {h.last_status_code??'—'}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>updateHook(h,{is_active:!h.is_active})} className={`rounded-lg border px-3 py-2 text-[11px] font-black ${card}`}>{h.is_active?'Pausar':'Ativar'}</button><button onClick={()=>testHook(h)} className={`rounded-lg border px-3 py-2 text-[11px] font-black ${card}`}>Testar</button><button onClick={()=>rotate(h)} className={`rounded-lg border px-3 py-2 text-[11px] font-black ${card}`}>Novo segredo</button><button onClick={()=>del(h)} className="rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-2 text-[11px] font-black text-red-300">Excluir</button></div></div></div>)}</div></section>
 <section className={`mt-4 rounded-3xl border p-5 ${card}`}><h2 className="font-black">Contrato V2</h2><p className={`mt-2 text-sm leading-6 ${muted}`}>Crie Checkouts com `POST /checkouts` usando `Idempotency-Key`. O webhook devolve `external_id`, cliente, metadata, origem e valores do pagamento. Assine/verifique o corpo bruto usando o header `X-PixWiki-Signature`.</p></section>
 </div><PixWikiDashboardNav dark={dark}/></main>
}
