-- PixWiki Fase 9 — API e Webhooks
-- Já aplicada no projeto Supabase de produção.

update public.pixwiki_plan_catalog
set features = coalesce(features,'{}'::jsonb) || '{"webhooks": true}'::jsonb, updated_at=now()
where plan='pro';

update public.pixwiki_plan_catalog
set features = coalesce(features,'{}'::jsonb) || '{"webhooks": false}'::jsonb, updated_at=now()
where plan in ('free','link');

create table if not exists public.pixwiki_api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  key_prefix text not null,
  key_hash text not null unique,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pixwiki_api_keys_name_check check (char_length(name) between 1 and 80),
  constraint pixwiki_api_keys_prefix_check check (char_length(key_prefix) between 6 and 32)
);
create index if not exists pixwiki_api_keys_user_idx on public.pixwiki_api_keys(user_id,created_at desc);
alter table public.pixwiki_api_keys enable row level security;

create table if not exists public.pixwiki_api_request_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  api_key_id uuid references public.pixwiki_api_keys(id) on delete set null,
  method text not null,
  path text not null,
  status_code integer not null,
  duration_ms integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists pixwiki_api_request_logs_key_time_idx on public.pixwiki_api_request_logs(api_key_id,created_at desc);
alter table public.pixwiki_api_request_logs enable row level security;

create table if not exists public.pixwiki_webhooks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id uuid references public.companies(id) on delete cascade,
  name text not null default 'Webhook',
  url text not null,
  is_active boolean not null default true,
  event_types text[] not null default array['pix.received']::text[],
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_status_code integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.pixwiki_webhooks enable row level security;

create table if not exists public.pixwiki_webhook_secrets (
  webhook_id uuid primary key references public.pixwiki_webhooks(id) on delete cascade,
  signing_secret text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz
);
alter table public.pixwiki_webhook_secrets enable row level security;

create table if not exists public.pixwiki_webhook_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  receipt_id uuid not null references public.mp_received_payments(id) on delete cascade,
  event_type text not null default 'pix.received',
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(receipt_id,event_type)
);
alter table public.pixwiki_webhook_events enable row level security;

create table if not exists public.pixwiki_webhook_deliveries (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.pixwiki_webhook_events(id) on delete cascade,
  webhook_id uuid not null references public.pixwiki_webhooks(id) on delete cascade,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  next_attempt_at timestamptz,
  response_status integer,
  response_body text,
  last_error text,
  delivered_at timestamptz,
  last_attempt_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id,webhook_id)
);
create index if not exists pixwiki_webhook_deliveries_due_idx on public.pixwiki_webhook_deliveries(status,next_attempt_at);

insert into public.pixwiki_internal_secrets(key,secret)
values('webhook_internal',replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-',''))
on conflict(key) do nothing;
