'use client';

import { useState } from 'react';
import { Loader2, Plus, Save, Trash2 } from 'lucide-react';
import type { ConviteConfig, InformacaoItem, ProgramacaoItem } from '@/lib/conviteria/tipos';

export default function DetalhesPainel({ eventoId, token, cfg, gestao, aoSalvar }: { eventoId: string; token: string; cfg: ConviteConfig; gestao: { rsvpRestrito: boolean; qrModo: 'familia' | 'individual' }; aoSalvar: (cfg: ConviteConfig, g: { rsvpRestrito: boolean; qrModo: 'familia' | 'individual' }) => void; }) {
  const [rsvpRestrito, setRsvp] = useState(gestao.rsvpRestrito); const [qrModo, setQr] = useState(gestao.qrModo); const [url, setUrl] = useState(cfg.listaPresentesExternaUrl ?? '');
  const [programacao, setProgramacao] = useState<ProgramacaoItem[]>(cfg.programacao ?? []); const [informacoes, setInformacoes] = useState<InformacaoItem[]>(cfg.informacoes ?? []); const [salvando, setSalvando] = useState(false); const [msg, setMsg] = useState('');
  async function salvar() {
    setSalvando(true); setMsg('');
    try {
      const r = await fetch('/api/conviteria/gestao', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ eventoId, rsvpRestrito, qrModo, listaPresentesExternaUrl: url, programacao, informacoes }) });
      const d = await r.json().catch(() => null); if (!r.ok) throw new Error(d?.erro || 'Não foi possível salvar.'); aoSalvar(d.config, { rsvpRestrito, qrModo }); setMsg('Alterações salvas.');
    } catch (e: any) { setMsg(e.message || 'Não foi possível salvar.'); } finally { setSalvando(false); }
  }
  return <section className="space-y-5">
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><h2 className="font-semibold">Confirmação de presença</h2><label className="mt-4 flex items-start gap-3"><input type="checkbox" checked={rsvpRestrito} onChange={(e) => setRsvp(e.target.checked)} className="mt-1" /><span><strong>Somente convidados cadastrados podem confirmar</strong><small className="block text-[#7c5560]">A pessoa localiza a família pelo e-mail ou telefone cadastrado e só pode marcar nomes da lista.</small></span></label><div className="mt-4"><p className="text-sm font-medium">QR padrão</p><div className="mt-2 flex gap-2"><button onClick={() => setQr('familia')} className={`rounded-xl px-3 py-2 text-sm ${qrModo === 'familia' ? 'bg-[#c06078] text-white' : 'bg-[#fff5f8]'}`}>Por família</button><button onClick={() => setQr('individual')} className={`rounded-xl px-3 py-2 text-sm ${qrModo === 'individual' ? 'bg-[#c06078] text-white' : 'bg-[#fff5f8]'}`}>Individual</button></div></div></div>
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><h2 className="font-semibold">Lista externa de presentes</h2><p className="mt-1 text-sm text-[#7c5560]">Cole somente a URL da lista em outra loja/site. Ela pode coexistir com os presentes do ConviteIA.</p><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://..." className="mt-3 w-full rounded-xl border border-[#c0607833] px-3 py-2.5" /></div>
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Programação</h2><p className="text-sm text-[#7c5560]">Cerimônia, recepção, jantar, parabéns e outros momentos.</p></div><button onClick={() => setProgramacao((p) => [...p, { id: crypto.randomUUID(), horario: '', titulo: '' }])} className="inline-flex items-center gap-1 rounded-lg bg-[#fff5f8] px-3 py-2 text-sm"><Plus className="h-4 w-4" />Adicionar</button></div><div className="mt-4 space-y-3">{programacao.map((p, i) => <div key={p.id} className="grid gap-2 rounded-xl bg-[#fff9fb] p-3 sm:grid-cols-[110px_1fr_auto]"><input value={p.horario} onChange={(e) => setProgramacao((xs) => xs.map((x, j) => j === i ? { ...x, horario: e.target.value } : x))} placeholder="19:30" className="rounded-lg border px-3 py-2" /><div className="space-y-2"><input value={p.titulo} onChange={(e) => setProgramacao((xs) => xs.map((x, j) => j === i ? { ...x, titulo: e.target.value } : x))} placeholder="Recepção" className="w-full rounded-lg border px-3 py-2" /><input value={p.descricao ?? ''} onChange={(e) => setProgramacao((xs) => xs.map((x, j) => j === i ? { ...x, descricao: e.target.value } : x))} placeholder="Descrição opcional" className="w-full rounded-lg border px-3 py-2" /></div><button onClick={() => setProgramacao((xs) => xs.filter((_, j) => j !== i))} className="p-2 text-red-500"><Trash2 className="h-4 w-4" /></button></div>)}</div></div>
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Informações aos convidados</h2><p className="text-sm text-[#7c5560]">Traje, crianças, estacionamento, transporte, hospedagem, fotos ou texto livre.</p></div><button onClick={() => setInformacoes((p) => [...p, { id: crypto.randomUUID(), tipo: 'outro', titulo: '', texto: '' }])} className="inline-flex items-center gap-1 rounded-lg bg-[#fff5f8] px-3 py-2 text-sm"><Plus className="h-4 w-4" />Adicionar</button></div><div className="mt-4 space-y-3">{informacoes.map((p, i) => <div key={p.id} className="grid gap-2 rounded-xl bg-[#fff9fb] p-3 sm:grid-cols-[150px_1fr_auto]"><select value={p.tipo} onChange={(e) => setInformacoes((xs) => xs.map((x, j) => j === i ? { ...x, tipo: e.target.value as InformacaoItem['tipo'] } : x))} className="rounded-lg border px-3 py-2"><option value="traje">Traje</option><option value="criancas">Crianças</option><option value="estacionamento">Estacionamento</option><option value="transporte">Transporte</option><option value="hospedagem">Hospedagem</option><option value="fotos">Fotos</option><option value="outro">Outro</option></select><div className="space-y-2"><input value={p.titulo} onChange={(e) => setInformacoes((xs) => xs.map((x, j) => j === i ? { ...x, titulo: e.target.value } : x))} placeholder="Título" className="w-full rounded-lg border px-3 py-2" /><textarea value={p.texto} onChange={(e) => setInformacoes((xs) => xs.map((x, j) => j === i ? { ...x, texto: e.target.value } : x))} placeholder="Informação" rows={2} className="w-full rounded-lg border px-3 py-2" /></div><button onClick={() => setInformacoes((xs) => xs.filter((_, j) => j !== i))} className="p-2 text-red-500"><Trash2 className="h-4 w-4" /></button></div>)}</div></div>
    <div className="flex items-center gap-3"><button onClick={salvar} disabled={salvando} className="inline-flex items-center gap-2 rounded-xl bg-[#c06078] px-5 py-3 font-semibold text-white">{salvando ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Salvar detalhes</button>{msg && <p className="text-sm text-[#7c5560]">{msg}</p>}</div>
  </section>;
}
