'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Loader2, Plus, Trash2, X } from 'lucide-react';

type Mesa={id:string;nome:string;capacidade:number;ordem:number;observacoes?:string|null}; type Pessoa={id:string;nome:string;status:string}; type Vinculo={mesa_id:string;convidado_lista_id:string};
export default function MesasPainel({eventoId,token}:{eventoId:string;token:string}){
 const [mesas,setMesas]=useState<Mesa[]>([]),[pessoas,setPessoas]=useState<Pessoa[]>([]),[vinculos,setVinculos]=useState<Vinculo[]>([]),[carregando,setCarregando]=useState(true),[erro,setErro]=useState('');const[nome,setNome]=useState(''),[cap,setCap]=useState(8);
 const carregar=useCallback(async()=>{setCarregando(true);const r=await fetch(`/api/conviteria/gestao/mesas?eventoId=${encodeURIComponent(eventoId)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const d=await r.json().catch(()=>null);if(r.ok){setMesas(d.mesas??[]);setPessoas(d.convidados??[]);setVinculos(d.vinculos??[])}else setErro(d?.erro||'Falha ao carregar.');setCarregando(false)},[eventoId,token]);useEffect(()=>{void carregar()},[carregar]);
 async function post(body:any){const r=await fetch('/api/conviteria/gestao/mesas',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({eventoId,...body})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.erro||'Falha.');await carregar()}
 async function criar(){if(!nome.trim())return;try{await post({acao:'salvar_mesa',nome,capacidade:cap,ordem:mesas.length*10});setNome('')}catch(e:any){setErro(e.message)}}
 const semMesa=useMemo(()=>pessoas.filter((p)=>!vinculos.some((v)=>v.convidado_lista_id===p.id)),[pessoas,vinculos]);
 return <section className="space-y-5"><div className="rounded-2xl border border-[#c0607833] bg-white p-5"><div className="flex flex-wrap items-end gap-2"><label className="grid gap-1 text-sm">Nome/número<input value={nome} onChange={(e)=>setNome(e.target.value)} placeholder="Mesa 1" className="rounded-xl border px-3 py-2"/></label><label className="grid gap-1 text-sm">Capacidade<input type="number" min={1} max={100} value={cap} onChange={(e)=>setCap(Number(e.target.value))} className="w-28 rounded-xl border px-3 py-2"/></label><button onClick={criar} className="inline-flex items-center gap-2 rounded-xl bg-[#c06078] px-4 py-2.5 font-semibold text-white"><Plus className="h-4 w-4"/>Adicionar mesa</button></div>{erro&&<p className="mt-3 text-sm text-red-600">{erro}</p>}</div>{carregando?<div className="grid place-items-center py-16"><Loader2 className="h-7 w-7 animate-spin"/></div>:<div className="grid gap-4 md:grid-cols-2">{mesas.map((m)=>{const ids=vinculos.filter((v)=>v.mesa_id===m.id).map((v)=>v.convidado_lista_id);const ocupantes=pessoas.filter((p)=>ids.includes(p.id));return <div key={m.id} className="rounded-2xl border border-[#c0607833] bg-white p-5"><div className="flex items-start justify-between"><div><h3 className="font-semibold">{m.nome}</h3><p className="text-sm text-[#7c5560]">{ocupantes.length}/{m.capacidade} lugares</p></div><button onClick={async()=>{if(confirm('Excluir esta mesa?')){await fetch(`/api/conviteria/gestao/mesas?eventoId=${eventoId}&id=${m.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});await carregar()}}} className="p-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 space-y-2">{ocupantes.map((p)=><div key={p.id} className="flex items-center justify-between rounded-lg bg-[#fff9fb] px-3 py-2 text-sm"><span>{p.nome}</span><button onClick={()=>post({acao:'remover_atribuicao',convidadoId:p.id})}><X className="h-4 w-4"/></button></div>)}</div>{ocupantes.length<m.capacidade&&<select defaultValue="" onChange={(e)=>{if(e.target.value)void post({acao:'atribuir',mesaId:m.id,convidadoId:e.target.value});e.currentTarget.value=''}} className="mt-3 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Adicionar convidado…</option>{semMesa.map((p)=><option key={p.id} value={p.id}>{p.nome}</option>)}</select>}</div>})}{mesas.length===0&&<div className="col-span-full py-12 text-center text-sm text-[#7c5560]">Crie a primeira mesa para começar o mapa de lugares.</div>}</div>}</section>
}
