'use client';

import { useCallback, useEffect, useState } from 'react';
import { Copy, ImagePlus, Loader2, Pencil, Plus, Trash2 } from 'lucide-react';

type Padrinho = { id:string; slug:string; nome:string; papel?:string|null; mensagem?:string|null; foto_url?:string|null; dress_code?:string|null; cores_recomendadas?:string[]; resposta:string; respondido_em?:string|null };
const vazio = { id:'', nome:'', papel:'', mensagem:'', fotoUrl:'', dressCode:'', cores:['#c8a0a8','#ead8dc'] };
export default function PadrinhosPainel({ eventoId, token, slug }: { eventoId:string; token:string; slug:string }) {
  const [lista,setLista]=useState<Padrinho[]>([]); const [form,setForm]=useState(vazio); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState(''); const [salvando,setSalvando]=useState(false);
  const carregar=useCallback(async()=>{setCarregando(true);const r=await fetch(`/api/conviteria/gestao/padrinhos?eventoId=${encodeURIComponent(eventoId)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const d=await r.json().catch(()=>null);if(r.ok)setLista(d.padrinhos??[]);else setErro(d?.erro??'Falha ao carregar.');setCarregando(false);},[eventoId,token]);
  useEffect(()=>{void carregar();},[carregar]);
  async function upload(file:File){const fd=new FormData();fd.set('eventoId',eventoId);fd.set('tipo','padrinho');fd.set('arquivo',file);const r=await fetch('/api/conviteria/upload',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const d=await r.json();if(!r.ok)throw new Error(d?.erro||'Falha no upload.');setForm((f)=>({...f,fotoUrl:d.url}));}
  async function salvar(){if(!form.nome.trim())return;setSalvando(true);setErro('');try{const r=await fetch('/api/conviteria/gestao/padrinhos',{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({eventoId,...form})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.erro||'Não foi possível salvar.');setForm(vazio);await carregar();}catch(e:any){setErro(e.message);}finally{setSalvando(false)}}
  async function excluir(id:string){if(!confirm('Excluir este convite individual?'))return;await fetch(`/api/conviteria/gestao/padrinhos?eventoId=${encodeURIComponent(eventoId)}&id=${encodeURIComponent(id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});await carregar();}
  function editar(p:Padrinho){setForm({id:p.id,nome:p.nome,papel:p.papel??'',mensagem:p.mensagem??'',fotoUrl:p.foto_url??'',dressCode:p.dress_code??'',cores:Array.isArray(p.cores_recomendadas)&&p.cores_recomendadas.length?p.cores_recomendadas:['#c8a0a8','#ead8dc']});}
  return <section className="grid gap-5 lg:grid-cols-[360px_1fr]">
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><h2 className="font-semibold">Convite individual</h2><div className="mt-4 grid gap-2"><input value={form.nome} onChange={(e)=>setForm({...form,nome:e.target.value})} placeholder="João & Maria" className="rounded-xl border px-3 py-2"/><input value={form.papel} onChange={(e)=>setForm({...form,papel:e.target.value})} placeholder="Padrinhos de casamento" className="rounded-xl border px-3 py-2"/><textarea rows={5} value={form.mensagem} onChange={(e)=>setForm({...form,mensagem:e.target.value})} placeholder="Mensagem personalizada" className="rounded-xl border px-3 py-2"/><textarea rows={3} value={form.dressCode} onChange={(e)=>setForm({...form,dressCode:e.target.value})} placeholder="Traje / orientação" className="rounded-xl border px-3 py-2"/><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-3 text-sm"><ImagePlus className="h-4 w-4"/>Foto<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e)=>{const f=e.target.files?.[0];if(f)void upload(f).catch((x)=>setErro(x.message));}}/></label>{form.fotoUrl&&<img src={form.fotoUrl} alt="" className="h-36 w-full rounded-xl object-cover"/>}<div><p className="mb-2 text-sm">Cores recomendadas</p><div className="flex gap-2">{form.cores.map((c,i)=><input key={i} type="color" value={c} onChange={(e)=>setForm({...form,cores:form.cores.map((x,j)=>j===i?e.target.value:x)})} className="h-9 w-12"/>)}</div></div><button onClick={salvar} disabled={salvando} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#c06078] px-4 py-3 font-semibold text-white">{salvando?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}{form.id?'Atualizar':'Criar convite'}</button></div>{erro&&<p className="mt-3 text-sm text-red-600">{erro}</p>}</div>
    <div className="rounded-2xl border border-[#c0607833] bg-white p-5"><h2 className="font-semibold">Padrinhos convidados</h2>{carregando?<div className="grid place-items-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<div className="mt-4 space-y-3">{lista.map((p)=>{const url=`https://${slug}.conviteia.com/padrinhos/${p.slug}`;return <div key={p.id} className="rounded-xl bg-[#fff9fb] p-4"><div className="flex gap-3">{p.foto_url&&<img src={p.foto_url} alt="" className="h-16 w-16 rounded-xl object-cover"/>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{p.nome}</p><p className="text-xs text-[#7c5560]">{p.resposta==='aceito'?'Aceito ❤️':'Aguardando resposta'}</p></div><div className="flex"><button onClick={()=>editar(p)} className="p-2"><Pencil className="h-4 w-4"/></button><button onClick={()=>excluir(p.id)} className="p-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-2 flex gap-2"><a href={url} target="_blank" rel="noreferrer" className="truncate text-xs text-[#a04a63]">{url}</a><button onClick={()=>navigator.clipboard.writeText(url)} title="Copiar"><Copy className="h-4 w-4"/></button></div></div></div></div>})}{lista.length===0&&<p className="py-10 text-center text-sm text-[#7c5560]">Nenhum convite individual criado.</p>}</div>}</div>
  </section>;
}
