import { createClient } from 'jsr:@supabase/supabase-js@2'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ONESIGNAL_APP_ID = Deno.env.get('PIXWIKI_ONESIGNAL_APP_ID') ?? ''
const ONESIGNAL_API_KEY = Deno.env.get('PIXWIKI_ONESIGNAL_REST_API_KEY') ?? ''
const headers = { 'Content-Type': 'application/json' }

type Channel = 'email' | 'push' | 'whatsapp'
type Status = 'sent' | 'skipped' | 'failed' | 'waiting_config'
type ChannelResult = { channel: Channel; status: Status; provider_message_id?: string|null; recipient?: string|null; error?: string|null }

function money(cents:number|null|undefined){ return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents??0)/100) }
async function getSecret(s:any,key:string){const{data,error}=await s.from('pixwiki_internal_secrets').select('secret').eq('key',key).maybeSingle();if(error||!data?.secret)throw new Error(`Segredo interno PixWiki indisponível: ${key}`);return String(data.secret)}
async function authenticateInternal(s:any,r:Request){return(r.headers.get('x-pixwiki-internal-key')??'')===await getSecret(s,'notify_internal')}
async function oldLog(s:any,id:string,c:Channel){const{data}=await s.from('pixwiki_notification_logs').select('id,status,attempts,provider_message_id,recipient,error').eq('receipt_id',id).eq('channel',c).maybeSingle();return data}
async function start(s:any,r:any,c:Channel,force:boolean){const o=await oldLog(s,r.id,c);if(o&&!force&&['sent','skipped','waiting_config'].includes(o.status))return{done:true,log:o};const attempts=Number(o?.attempts??0)+1,now=new Date().toISOString();const{data,error}=await s.from('pixwiki_notification_logs').upsert({receipt_id:r.id,company_id:r.company_id,user_id:r.user_id,channel:c,status:'processing',attempts,last_attempt_at:now,error:null,updated_at:now},{onConflict:'receipt_id,channel'}).select('id,status,attempts').single();if(error)throw error;return{done:false,log:data}}
async function finish(s:any,id:string,r:ChannelResult){const now=new Date().toISOString(),u:any={status:r.status,provider_message_id:r.provider_message_id??null,recipient:r.recipient??null,error:r.error?String(r.error).slice(0,1500):null,updated_at:now};if(r.status==='sent')u.sent_at=now;await s.from('pixwiki_notification_logs').update(u).eq('receipt_id',id).eq('channel',r.channel)}
async function email(r:any,secret:string):Promise<ChannelResult>{const x=await fetch(`${SUPABASE_URL}/functions/v1/pixwiki-send-email`,{method:'POST',headers:{'Content-Type':'application/json','x-pixwiki-internal-key':secret},body:JSON.stringify({receipt_id:r.id})}),p=await x.json().catch(()=>({}));if(!x.ok||p?.ok===false)return{channel:'email',status:'failed',error:p?.error??`HTTP ${x.status}`};if(p?.skipped)return{channel:'email',status:'skipped',recipient:p?.recipient??null,error:p?.reason??null};return{channel:'email',status:'sent',recipient:p?.recipient??null,provider_message_id:p?.provider_message_id??null}}
async function push(s:any,r:any,name:string):Promise<ChannelResult>{if(!ONESIGNAL_APP_ID||!ONESIGNAL_API_KEY)return{channel:'push',status:'waiting_config',error:'OneSignal PixWiki ainda não configurado'};const{data:rows}=await s.from('pixwiki_push_subscriptions').select('subscription_id').eq('user_id',r.user_id).eq('is_active',true),ids=(rows??[]).map((x:any)=>String(x.subscription_id)).filter(Boolean);if(!ids.length)return{channel:'push',status:'skipped',recipient:String(r.user_id),error:'Usuário ainda não assinou Push no PixWiki'};const label=r.source==='pixwiki_link'?'Pix Link':'Chave Pix',amount=money(r.amount_cents);const x=await fetch('https://api.onesignal.com/notifications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Key ${ONESIGNAL_API_KEY}`},body:JSON.stringify({app_id:ONESIGNAL_APP_ID,include_subscription_ids:ids,headings:{pt:'Pix recebido ✅',en:'Pix recebido ✅'},contents:{pt:`${amount} · ${name} · ${label}`,en:`${amount} · ${name} · ${label}`},url:'https://pix.wiki/dashboard',data:{receipt_id:r.id,company_id:r.company_id,source:r.source},idempotency_key:String(r.id)})}),p=await x.json().catch(()=>({})),e=JSON.stringify(p?.errors??p??{http:x.status});if(!x.ok||p?.errors){if(e.includes('All included players are not subscribed'))return{channel:'push',status:'skipped',recipient:`${ids.length} dispositivo(s)`,error:'Subscriptions registradas não estão mais inscritas no OneSignal'};return{channel:'push',status:'failed',recipient:`${ids.length} dispositivo(s)`,error:e.slice(0,1200)}}if(!p?.id)return{channel:'push',status:'skipped',recipient:`${ids.length} dispositivo(s)`,error:'Nenhuma assinatura Push válida para este usuário'};return{channel:'push',status:'sent',provider_message_id:String(p.id),recipient:`${ids.length} dispositivo(s)`}}
async function whatsapp(r:any,secret:string):Promise<ChannelResult>{const x=await fetch(`${SUPABASE_URL}/functions/v1/pixwiki-send-whatsapp`,{method:'POST',headers:{'Content-Type':'application/json','x-pixwiki-internal-key':secret},body:JSON.stringify({receipt_id:r.id})}),p=await x.json().catch(()=>({}));if(!x.ok||p?.ok===false)return{channel:'whatsapp',status:'failed',error:p?.error??`HTTP ${x.status}`};if(p?.skipped)return{channel:'whatsapp',status:'skipped',recipient:p?.destination_suffix?`••••${p.destination_suffix}`:null,error:p?.reason??null};return{channel:'whatsapp',status:'sent',provider_message_id:p?.provider_message_id??null,recipient:p?.destination_suffix?`••••${p.destination_suffix}`:null,error:p?.mode?`mode:${p.mode}`:null}}
async function webhook(s:any,id:string){const sec=await getSecret(s,'webhook_internal'),x=await fetch(`${SUPABASE_URL}/functions/v1/pixwiki-webhook-dispatch`,{method:'POST',headers:{'Content-Type':'application/json','x-pixwiki-internal-key':sec},body:JSON.stringify({receipt_id:id})}),p=await x.json().catch(()=>({}));return{ok:x.ok&&p?.ok!==false,status:x.status,payload:p}}
Deno.serve(async r=>{if(r.method!=='POST')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers});const s=createClient(SUPABASE_URL,SERVICE_ROLE);try{if(!(await authenticateInternal(s,r)))return new Response(JSON.stringify({error:'not_found'}),{status:404,headers});const sec=await getSecret(s,'notify_internal'),b=await r.json().catch(()=>({})),id=String(b?.receipt_id??''),historical=b?.allow_historical===true,force=b?.force_retry===true,only:Channel[]|null=Array.isArray(b?.channels)?b.channels.filter((x:unknown)=>['email','push','whatsapp'].includes(String(x))) as Channel[]:null;if(!id)return new Response(JSON.stringify({error:'receipt_id_required'}),{status:400,headers});const{data:receipt}=await s.from('mp_received_payments').select('id,company_id,user_id,amount_cents,fee_amount_cents,net_amount_cents,source,status,notification_eligible,notified_at').eq('id',id).maybeSingle();if(!receipt)return new Response(JSON.stringify({error:'receipt_not_found'}),{status:404,headers});if(!historical&&!receipt.notification_eligible)return new Response(JSON.stringify({ok:true,skipped:true,reason:'historical_receipt'}),{headers});if(receipt.status!=='approved')return new Response(JSON.stringify({ok:true,skipped:true,reason:'not_approved'}),{headers});const[{data:settings},{data:company}]=await Promise.all([s.from('pixwiki_notification_settings').select('email_enabled,push_enabled,whatsapp_enabled').eq('company_id',receipt.company_id).maybeSingle(),s.from('companies').select('name').eq('id',receipt.company_id).maybeSingle()]),enabled:Channel[]=[];if(settings?.email_enabled!==false)enabled.push('email');if(settings?.push_enabled!==false)enabled.push('push');if(settings?.whatsapp_enabled===true)enabled.push('whatsapp');const channels=only?enabled.filter(c=>only.includes(c)):enabled,out:ChannelResult[]=[];for(const c of channels){const st=await start(s,receipt,c,force);if(st.done){out.push({channel:c,status:st.log.status as Status,provider_message_id:st.log.provider_message_id,recipient:st.log.recipient,error:st.log.error});continue}let result:ChannelResult;try{result=c==='email'?await email(receipt,sec):c==='push'?await push(s,receipt,company?.name||'Seu recebedor'):await whatsapp(receipt,sec)}catch(e){result={channel:c,status:'failed',error:e instanceof Error?e.message:'Erro desconhecido'}}await finish(s,receipt.id,result);out.push(result)}let wh:any=null;if(receipt.notification_eligible===true){try{wh=await webhook(s,receipt.id)}catch(e){wh={ok:false,error:e instanceof Error?e.message:'webhook_dispatch_failed'}}}const now=new Date().toISOString();await s.from('mp_received_payments').update({notified_at:now,updated_at:now}).eq('id',receipt.id);return new Response(JSON.stringify({ok:true,receipt_id:receipt.id,results:out,webhook:wh}),{headers})}catch(e){const m=e instanceof Error?e.message:'Erro interno';console.error('[pixwiki-notify]',m);return new Response(JSON.stringify({ok:false,error:m}),{status:500,headers})}})
